### ISSUE TITLE
Does this work on a wyzehacked v3 firmware 4.36.2.5 ?

### ISSUE THREAD

**Issue by virmaior** [gtxaspec/wz_mini_hacks#1]
For some reason, my SD cards don't read correctly on 4.36.0.280. Did the filesystem change from 4.36.0.280 to 4.36.2.5?

I have my cameras completely disconnected from internet which means no live feed and it'd be nice to get them back to giving a feed (though a bit worried about letting the app even have access to them even with the update blocking feature)

**Comment by gtxaspec** [comment]
yes, if you can enable telnet, it will work.

**Comment by gtxaspec** [comment]
Telnet or DNS spoofing is not required anymore for installation.
