### ISSUE TITLE
cmd waitMotion returning "error : wait motion error"

### ISSUE THREAD

**Issue by jacoblukewood** [gtxaspec/wz_mini_hacks#101]
New setup, everything working well. Running `cmdWaitMotion 1000` over SSH return the following error: `error : wait motion error`.

V3 camera

**Comment by gtxaspec** [comment]
i just discovered you must have "motion tagging" enabled in the app to have this command work.  Can you try that and see if it works?

**Comment by jacoblukewood** [comment]
Enabling motion tagging in the app and rebooting the camera solved the issue. Thanks!
