### ISSUE TITLE
RTSP: Cannot init device:/dev/video2

### ISSUE THREAD

**Issue by michaelgaultjr** [gtxaspec/wz_mini_hacks#102]
Hello,

I'm having some trouble getting RTSP working on my Wyze Cam v3 Spotlight camera (Firmware version 4.61.0.3).

`wz_init.log` and `wz_post.log` and didn't have any errors, but I found this error in `wz_user.log`

```
[NOTICE] /root/CLEAN/v4l2rtspserver/main.cpp:297
        Version: 0.3.3-4-ga43e094-dirty live555 version:2022.04.26
[NOTICE] /root/CLEAN/v4l2rtspserver/src/V4l2RTSPServer.cpp:37
        Create V4L2 Source.../dev/video2
[NOTICE] /root/CLEAN/v4l2rtspserver/v4l2wrapper/src/V4l2Device.cpp:133
        driver:v4l2 loopback capabilities:85008003 mandatory:4000001
[NOTICE] /root/CLEAN/v4l2rtspserver/v4l2wrapper/src/V4l2Device.cpp:135
        /dev/video2 support output
[NOTICE] /root/CLEAN/v4l2rtspserver/v4l2wrapper/src/V4l2Device.cpp:136
        /dev/video2 support capture
[NOTICE] /root/CLEAN/v4l2rtspserver/v4l2wrapper/src/V4l2Device.cpp:138
        /dev/video2 support read/write
[NOTICE] /root/CLEAN/v4l2rtspserver/v4l2wrapper/src/V4l2Device.cpp:139
        /dev/video2 support streaming
[ERROR] /root/CLEAN/v4l2rtspserver/v4l2wrapper/src/V4l2Device.cpp:192
        /dev/video2: Cannot get format Invalid argument
[ERROR] /root/CLEAN/v4l2rtspserver/v4l2wrapper/src/V4l2Device.cpp:192
        /dev/video2: Cannot get format Invalid argument
[ERROR] /root/CLEAN/v4l2rtspserver/v4l2wrapper/src/V4l2Device.cpp:192
        /dev/video2: Cannot get format Invalid argument
[ERROR] /root/CLEAN/v4l2rtspserver/v4l2wrapper/src/V4l2Device.cpp:83
        Cannot init device:/dev/video2
[NOTICE] /root/CLEAN/v4l2rtspserver/v4l2wrapper/src/V4l2MmapDevice.cpp:141
        Device /dev/video2+ event=n
```

Manually running `LD_LIBRARY_PATH=/opt/wz_mini/lib /opt/wz_mini/bin/v4l2rtspserver -U username:password -P 8554 /dev/video2` gives the same error.

<details>
<summary>Full <code>wz_user.log</code></summary>
<pre>
<code>
+ echo 'welcome to wz_user.sh'
welcome to wz_user.sh
+ echo 'PID 119'
PID 119
+ '[[' -e /tmp/dbgflag ]]
+ export 'WZMINI_CFG=/opt/wz_mini/wz_mini.conf'
+ '[' -f /opt/wz_mini/wz_mini.conf ]
+ source /opt/wz_mini/wz_mini.conf
+ WEB_CAM_ENABLE=false
+ WEB_CAM_BIT_RATE=8000
+ WEB_CAM_FPS_RATE=25
+ CUSTOM_HOSTNAME=WCV3SPOTLIGHT
+ ENABLE_USB_ETH=false
+ ENABLE_USB_ETH_MODULES=asix
+ ENABLE_USB_DIRECT=false
+ USB_DIRECT_MAC_ADDR=02:01:02:03:04:08
+ ENABLE_USB_RNDIS=false
+ ENABLE_IPV6=false
+ ENABLE_WIREGUARD=false
+ WIREGUARD_IPV4=
+ WIREGUARD_PEER_ENDPOINT=
+ WIREGUARD_PEER_PUBLIC_KEY=
+ WIREGUARD_PEER_ALLOWED_IPS=
+ WIREGUARD_PEER_KEEP_ALIVE=
+ ENABLE_IPTABLES=false
+ ENABLE_NFSv4=true
+ ENABLE_RTL8189FS_DRIVER=false
+ REMOTE_SPOTLIGHT=false
+ REMOTE_SPOTLIGHT_HOST=0.0.0.0
+ RTSP_LOGIN=[redacted]
+ RTSP_PASSWORD=[redacted]
+ RTSP_PORT=8554
+ RTSP_HI_RES_ENABLED=false
+ RTSP_HI_RES_ENABLE_AUDIO=false
+ RTSP_HI_RES_FPS=
+ RTSP_HI_RES_MAX_BITRATE=
+ RTSP_HI_RES_TARGET_BITRATE=
+ RTSP_HI_RES_ENC_PARAMETER=
+ RTSP_LOW_RES_ENABLED=true
+ RTSP_LOW_RES_ENABLE_AUDIO=false
+ RTSP_LOW_RES_FPS=15
+ RTSP_LOW_RES_MAX_BITRATE=2048
+ RTSP_LOW_RES_TARGET_BITRATE=1024
+ RTSP_LOW_RES_ENC_PARAMETER=2
+ RTMP_STREAM_ENABLED=false
+ RTMP_STREAM_FEED=video1_unicast
+ RMTP_STREAM_SERVICE=youtube
+ RTMP_STREAM_DISABLE_AUDIO=false
+ RTMP_STREAM_YOUTUBE_KEY=
+ RTMP_STREAM_TWITCH_KEY=
+ RTMP_STREAM_FACEBOOK_KEY=
+ ENABLE_SWAP=true
+ ENABLE_USB_STORAGE=false
+ ENABLE_EXT4=false
+ ENABLE_CIFS=false
+ DISABLE_FW_UPGRADE=false
+ AUDIO_PROMPT_VOLUME=50
+ ENABLE_MP4_WRITE=false
+ DEBUG_ENABLED=false
+ DEBUG_INITRAMFS_ENABLED=false
+ DEBUG_PASSWORD=false
+ CUSTOM_SCRIPT_PATH=
+ first_run_check
+ '[' -e /opt/wz_mini/tmp/.wz_user_firstrun ]
+ wait_wlan
+ true
+ ifconfig wlan0
+ grep 'inet addr'
ifconfig: wlan0: error fetching interface information: Device not found
+ grep 'inet addr'
+ ifconfig wlan0
ifconfig: wlan0: error fetching interface information: Device not found
+ echo ' wlan0 not ready yet...'
 wlan0 not ready yet...
+ sleep 5
+ true
+ grep 'inet addr'
+ ifconfig wlan0
+ grep 'inet addr'
+ ifconfig wlan0
+ echo ' wlan0 not ready yet...'
 wlan0 not ready yet...
+ sleep 5
+ true
+ grep 'inet addr'
+ ifconfig wlan0
+ grep 'inet addr'
+ ifconfig wlan0
+ echo ' wlan0 not ready yet...'
 wlan0 not ready yet...
+ sleep 5
+ true
+ grep 'inet addr'
+ ifconfig wlan0
          inet addr:192.168.1.97  Bcast:192.168.1.255  Mask:255.255.255.0
+ store_mac
+ echo 'store original mac'
store original mac
+ tr '[:lower:]' '[:upper:]'
+ cat /sys/class/net/wlan0/address
+ break
+ '[' -f /opt/wz_mini/tmp/.T20 ]
+ KMOD_PATH=/opt/wz_mini/lib/modules/3.10.14__isvp_swan_1.0__
+ swap_enable
+ '[' -e /opt/wz_mini/swap ]
+ echo 'Swap file exists'
Swap file exists
+ grep mini
+ cat /proc/swaps
/opt/wz_mini/swap                       file            131068  0       -1
+ echo 'Swap is already enabled'
Swap is already enabled
+ '[[' false '==' true ]]
+ echo 'ipv6 disabled'
ipv6 disabled
+ sysctl -w 'net.ipv6.conf.all.disable_ipv6=1'
net.ipv6.conf.all.disable_ipv6 = 1
+ '[[' true '==' true ]]
+ insmod /opt/wz_mini/lib/modules/3.10.14__isvp_swan_1.0__/kernel/lib/oid_registry.ko
+ insmod /opt/wz_mini/lib/modules/3.10.14__isvp_swan_1.0__/kernel/net/dns_resolver/dns_resolver.ko
+ insmod /opt/wz_mini/lib/modules/3.10.14__isvp_swan_1.0__/kernel/fs/nfs/nfsv4.ko
+ insmod /opt/wz_mini/lib/modules/3.10.14__isvp_swan_1.0__/kernel/net/sunrpc/auth_gss/auth_rpcgss.ko
+ echo nfsv4 enabled
nfsv4 enabled
+ '[[' false '==' true ]]
+ echo 'iptables disabled'
iptables disabled
+ '[[' false '==' true ]]
+ echo 'usb ethernet disabled'
usb ethernet disabled
+ '[[' false '==' true ]]
+ echo 'usb direct disabled'
usb direct disabled
+ '[[' false '==' true ]]
+ echo 'usb direct disabled'
usb direct disabled
+ '[[' false '==' true ]]
+ echo 'wireguard disabled'
wireguard disabled
+ '[[' false '==' true ]]
+ echo 'cifs disabled'
cifs disabled
+ '[[' false '==' true ]]
+ echo 'usb_storage disabled'
usb_storage disabled
+ '[[' false '==' true ]]
+ echo 'ext4 disabled'
ext4 disabled
+ '[[' false '==' true ]]
+ mkdir /tmp/Upgrade
+ '[[' false '==' true ]]
+ echo 'remote accessory disabled'
remote accessory disabled
+ '[[' false '==' true ]]
+ echo 'mp4 write disabled'
mp4 write disabled
+ '[[' false '==' true ]]
+ echo 'rtsp disabled'
rtsp disabled
+ '[[' true '==' true ]]
+ '[' -f /opt/wz_mini/tmp/.T20 ]
+ LOW_VIDEO_DEV=/dev/video2
+ swap_enable
+ '[' -e /opt/wz_mini/swap ]
+ echo 'Swap file exists'
Swap file exists
+ cat /proc/swaps
+ grep mini
+ /opt/wz_mini/bin/busybox inotifyd /opt/wz_mini/usr/bin/watch_up.sh /tmp:n
/opt/wz_mini/swap                       file            131068  0       -1
+ echo 'Swap is already enabled'
Swap is already enabled
+ /opt/wz_mini/bin/cmd video on1
ok
+ '[[' [redacted] '='  ]]
+ '[[' false '==' true ]]
+ DEVICE2=/dev/video2
+ echo 'rtsp audio disabled'
rtsp audio disabled
+ '[[' 2 '!='  ]]
+ '[' -f /opt/wz_mini/tmp/.T20 ]
+ '[[' 2 '=~' '^[0|1|2|4|8]$' ]]
+ '[[' 2048 '!='  ]]
+ '[' -f /opt/wz_mini/tmp/.T20 ]
+ '[[' 1024 '!='  ]]
+ '[' -f /opt/wz_mini/tmp/.T20 ]
+ '[[' 15 '!='  ]]
+ '[' -f /opt/wz_mini/tmp/.T20 ]
+ '[[' true '==' true ]]
+ echo 'delay RTSP for iCamera'
delay RTSP for iCamera
+ sleep 5
+ watch -n30 -t '/system/bin/impdbg --enc_rc_s 1:80:4:15'
+ watch -n30 -t '/system/bin/impdbg --enc_rc_s 1:48:4:1024'
+ watch -n30 -t '/system/bin/impdbg --enc_rc_s 1:52:4:2048'
+ watch -n30 -t '/system/bin/impdbg --enc_rc_s 1:44:4:2'
+ event=n
+ directory=/tmp
+ file=18.mp4
+ date
Fri Jun 17 21:18:38 UTC 2022
+ '[[' 18.mp4 '==' img ]]
+ event=n
+ directory=/tmp
+ file=kvs
+ date
Fri Jun 17 21:18:38 UTC 2022
+ '[[' kvs '==' img ]]
+ event=n
+ directory=/tmp
+ file=aws_iot
+ date
Fri Jun 17 21:18:38 UTC 2022
+ '[[' aws_iot '==' img ]]
+ '[[' true '==' true ]]
+ '[[' false '==' true ]]
+ hostname_set
+ echo 'set hostname'
set hostname
+ hostname WCV3SPOTLIGHT
+ LD_LIBRARY_PATH=/opt/wz_mini/lib /opt/wz_mini/bin/v4l2rtspserver -U [redacted]:[redacted] -P 8554 /dev/video2
+ touch /opt/wz_mini/tmp/.wz_user_firstrun
+ pkill -f dumpload
+ sysctl -w 'kernel.core_pattern=|/bin/false'
kernel.core_pattern = |/bin/false
+ dmesg_log
+ DMESG_LOG=/opt/wz_mini/log/dmesg
+ '[[' -e /opt/wz_mini/log/dmesg.log '||' -L /opt/wz_mini/log/dmesg.log ]]
+ i=0
+ '[[' -e /opt/wz_mini/log/dmesg.log.0 '||' -L /opt/wz_mini/log/dmesg.log.0 ]]
+ let i++
+ '[[' -e /opt/wz_mini/log/dmesg.log.1 '||' -L /opt/wz_mini/log/dmesg.log.1 ]]
+ mv /opt/wz_mini/log/dmesg.log /opt/wz_mini/log/dmesg.log.1
+ DMESG_LOG=/opt/wz_mini/log/dmesg
+ touch -- /opt/wz_mini/log/dmesg.log
+ dmesg
+ trim_logs
+ echo 'Deleting logs older than 5 boots...'
Deleting logs older than 5 boots...
+ read file
+ find /opt/wz_mini/log -name '*log*'
+ '[' /opt/wz_mini/log -gt 5 ]
sh: /opt/wz_mini/log: out of range
+ read file
+ '[' /opt/wz_mini/log/wz_init.log -gt 5 ]
sh: /opt/wz_mini/log/wz_init.log: out of range
+ read file
+ '[' /opt/wz_mini/log/wz_post.log -gt 5 ]
sh: /opt/wz_mini/log/wz_post.log: out of range
+ read file
+ '[' /opt/wz_mini/log/wz_user.log -gt 5 ]
sh: /opt/wz_mini/log/wz_user.log: out of range
+ read file
+ '[' /opt/wz_mini/log/dmesg.log -gt 5 ]
sh: /opt/wz_mini/log/dmesg.log: out of range
+ read file
+ '[' 0 -gt 5 ]
+ read file
+ '[' 0 -gt 5 ]
+ read file
+ '[' 0 -gt 5 ]
+ read file
+ '[' 0 -gt 5 ]
+ read file
+ '[' 1 -gt 5 ]
+ read file
+ '[' 1 -gt 5 ]
+ read file
+ '[' 1 -gt 5 ]
+ read file
+ '[' 1 -gt 5 ]
+ read file
+ sync
+ echo 3
+ '[' -f  ]
+ echo 'custom script not found'
custom script not found
+ echo 'wz_user.sh done'
log level:500
VIDIOC_STREAMOFF: Bad file descriptor
VIDIOC_REQBUFS: Bad file descriptor

[NOTICE] /root/CLEAN/v4l2rtspserver/main.cpp:297
        Version: 0.3.3-4-ga43e094-dirty live555 version:2022.04.26
[NOTICE] /root/CLEAN/v4l2rtspserver/src/V4l2RTSPServer.cpp:37
        Create V4L2 Source.../dev/video2
[NOTICE] /root/CLEAN/v4l2rtspserver/v4l2wrapper/src/V4l2Device.cpp:133
        driver:v4l2 loopback capabilities:85008003 mandatory:4000001
[NOTICE] /root/CLEAN/v4l2rtspserver/v4l2wrapper/src/V4l2Device.cpp:135
        /dev/video2 support output
[NOTICE] /root/CLEAN/v4l2rtspserver/v4l2wrapper/src/V4l2Device.cpp:136
        /dev/video2 support capture
[NOTICE] /root/CLEAN/v4l2rtspserver/v4l2wrapper/src/V4l2Device.cpp:138
        /dev/video2 support read/write
[NOTICE] /root/CLEAN/v4l2rtspserver/v4l2wrapper/src/V4l2Device.cpp:139
        /dev/video2 support streaming
[ERROR] /root/CLEAN/v4l2rtspserver/v4l2wrapper/src/V4l2Device.cpp:192
        /dev/video2: Cannot get format Invalid argument
[ERROR] /root/CLEAN/v4l2rtspserver/v4l2wrapper/src/V4l2Device.cpp:192
        /dev/video2: Cannot get format Invalid argument
[ERROR] /root/CLEAN/v4l2rtspserver/v4l2wrapper/src/V4l2Device.cpp:192
        /dev/video2: Cannot get format Invalid argument
[ERROR] /root/CLEAN/v4l2rtspserver/v4l2wrapper/src/V4l2Device.cpp:83
        Cannot init device:/dev/video2
[NOTICE] /root/CLEAN/v4l2rtspserver/v4l2wrapper/src/V4l2MmapDevice.cpp:141
        Device /dev/video2+ event=n
+ directory=/tmp
+ file=webrtc
+ date
Fri Jun 17 21:18:39 UTC 2022
+ '[[' webrtc '==' img ]]
+ event=n
+ directory=/tmp
+ file=19.mp4
+ date
Fri Jun 17 21:19:02 UTC 2022
+ '[[' 19.mp4 '==' img ]]
+ event=n
+ directory=/tmp
+ file=20.mp4
+ date
Fri Jun 17 21:20:01 UTC 2022
+ '[[' 20.mp4 '==' img ]]
+ event=n
+ directory=/tmp
+ file=21.mp4
+ date
Fri Jun 17 21:21:01 UTC 2022
+ '[[' 21.mp4 '==' img ]]
+ event=n
+ directory=/tmp
+ file=22.mp4
+ date
Fri Jun 17 21:22:01 UTC 2022
+ '[[' 22.mp4 '==' img ]]
+ event=n
+ directory=/tmp
+ file=23.mp4
+ date
Fri Jun 17 21:23:01 UTC 2022
+ '[[' 23.mp4 '==' img ]]
+ event=n
+ directory=/tmp
+ file=24.mp4
+ date
Fri Jun 17 21:24:01 UTC 2022
+ '[[' 24.mp4 '==' img ]]
+ event=n
+ directory=/tmp
+ file=25.mp4
+ date
Fri Jun 17 21:25:01 UTC 2022
+ '[[' 25.mp4 '==' img ]]
+ event=n
+ directory=/tmp
+ file=26.mp4
+ date
Fri Jun 17 21:26:01 UTC 2022
+ '[[' 26.mp4 '==' img ]]
+ event=n
+ directory=/tmp
+ file=27.mp4
+ date
Fri Jun 17 21:27:01 UTC 2022
+ '[[' 27.mp4 '==' img ]]
+ event=n
+ directory=/tmp
+ file=28.mp4
+ date
Fri Jun 17 21:28:01 UTC 2022
+ '[[' 28.mp4 '==' img ]]
+ event=n
+ directory=/tmp
+ file=29.mp4
+ date
Fri Jun 17 21:29:01 UTC 2022
+ '[[' 29.mp4 '==' img ]]
+ event=n
+ directory=/tmp
+ file=30.mp4
+ date
Fri Jun 17 21:30:01 UTC 2022
+ '[[' 30.mp4 '==' img ]]
+ event=n
+ directory=/tmp
+ file=31.mp4
+ date
Fri Jun 17 21:31:01 UTC 2022
+ '[[' 31.mp4 '==' img ]]
</code>
</pre>
</details>

**Comment by gtxaspec** [comment]
need more logs.  run gather_wz_logs.sh, you can check the logs there or share here so we can analyze then

**Comment by michaelgaultjr** [comment]
Not exactly sure what to look for so here's the logs zip

[log_gather_2022-06-17_T2206.tar.gz](https://github.com/gtxaspec/wz_mini_hacks/files/8931537/log_gather_2022-06-17_T2206.tar.gz)

**Comment by gtxaspec** [comment]
the problem is your firmware version, go on the wyze website and download the latest firmware, flash it, and it should work.  there's an issue using the more with the old rtsp firmware version

**Comment by michaelgaultjr** [comment]
> a

That worked, however I cannot view the stream. I'm using VLC with this URL `rtsp://[username]:[password]@192.168.1.[redacted]:8554/unicast` and it just times out and doesn't give any errors, any other URL fails.
