### ISSUE TITLE
Add wiki page

### ISSUE THREAD

**Issue by archandanime** [gtxaspec/wz_mini_hacks#127]
I think it's a good idea make to wiki pages so it's easier to read and the README.md won't be too long.
It's easier to add more contents too.

**Comment by archandanime** [comment]
@gtxaspec I can't add wiki pages or make pull request for wiki pages from my cloned repo

**Comment by gtxaspec** [comment]
from `https://github.com/gtxaspec/wz_mini_hacks.wiki.git` ?

**Comment by archandanime** [comment]
let me try it again

**Comment by tensiondriven** [comment]
As a counterpoint, having the documentation in source control makes a lot of sense to me.

I agree that the readme could be improved and split out into multiple files, but I do not think divorcing the docs from git would be an improvement.

The good news is that any one of us could update the docs and submit a pull request to improve this with minimal technical expertise.

**Comment by gtxaspec** [comment]
wiki added.
