### ISSUE TITLE
v2 support?

### ISSUE THREAD

**Issue by gluedots** [gtxaspec/wz_mini_hacks#13]
Saw this posted on reddit where someone said the v2 was also supported, but I don't see any mention of the v2.

Would I just follow the instructions for the v3?

**Comment by gtxaspec** [comment]
No, it doesn't work for V2.

See https://github.com/Dafang-Hacks/Xiaomi-Dafang-Hacks for the V2

**Comment by gluedots** [comment]
Could support for the v2 be added in the future?

**Comment by virmaior** [comment]
for v2, why not https://github.com/openmiko/openmiko ?
I think the pedigree from this project winds up being partially derived from that because atomcam_tools is partially derived form that and this is partially derived from atomcam_tools

**Comment by gtxaspec** [comment]
will look into this at a later time.

**Comment by gtxaspec** [comment]
@gluedots v2 now supported.

**Comment by gluedots** [comment]
Thanks, will give it a try.
