### ISSUE TITLE
add function to libcallback to stop motor controls on panv2

### ISSUE THREAD

**Issue by gtxaspec** [gtxaspec/wz_mini_hacks#133]
find the function, hook it to stop motor init.

**Comment by gtxaspec** [comment]
`local_sdk_motor_init`

**Comment by endertable** [comment]
Hi @gtxaspec Forgive my ignorance, just asking because I am confused, but why exactly would one want to stop motor controls on a PTZ (minus the Z)?  Since you are working on it I know there would be a specific reason, I just can't think of it.

**Comment by gtxaspec** [comment]
it was a request 
https://github.com/gtxaspec/wz_mini_hacks/discussions/132

**Comment by gtxaspec** [comment]
added in https://github.com/gtxaspec/wz_mini_hacks/commit/d87d43241fbd04e4b7304e2aca94d42dbab088dd

**Comment by claudobahn** [comment]
@gtxaspec noticed you removed all the sources for libcallback as part of the commit for this (https://github.com/gtxaspec/wz_mini_hacks/commit/d87d43241fbd04e4b7304e2aca94d42dbab088dd). Any chance you could restore that?

Seems like a useful piece of source code for expanding functionality.
