### ISSUE TITLE
How to add user for non-root NFS mounts

### ISSUE THREAD

**Issue by fabriziorizzo** [gtxaspec/wz_mini_hacks#14]
remote NFS v4 volume requires specific UID/GID (1007/1007), does not allow root.  How can NFS mounts be configured / executed from your script  with the correct UID/GID to allow access?

**Comment by endertable** [comment]
At the bottom of run_mmc.sh script (before the NFS mount command) you can add something like the following:

cp /etc/passwd /opt/wz_mini/tmp/.storage/passwd
mount --bind /opt/wz_mini/tmp/.storage/passwd /etc/passwd

grep -q 'nfsuser:x:1007:1007:' /etc/passwd
if [ $? != 0 ]; then
  echo 'nfsuser:x:1007:1007:NFS Pseudo User:/:/bin/sh'   >> /etc/passwd
  # echo 'nfsuser:1007:x' >> /etc/group
fi


Not sure if you would have to populate the /etc/group file also?!?  But if you do, bind it like with /etc/passwd, then uncomment the line in the if-then routine.

**Comment by gtxaspec** [comment]
@fabriziorizzo I don't think I have nfsv4 enabled in the kernel...is this something you still need?

**Comment by fabriziorizzo** [comment]
> @fabriziorizzo I don't think I have nfsv4 enabled in the kernel...is this something you still need?

Yes please.

**Comment by gtxaspec** [comment]
@fabriziorizzo check the latest release for NFSv4 support, let me know if it works for you.

**Comment by gtxaspec** [comment]
let me know if you have any problems, closing for now. @fabriziorizzo

**Comment by fabriziorizzo** [comment]
Thank you.  have not had time to test yet.

--
F.
