### ISSUE TITLE
strip wifi kernel modules of debug symbols

### ISSUE THREAD

**Issue by gtxaspec** [gtxaspec/wz_mini_hacks#146]
add --strip-debug to compile process for 8189x and atbm603x
reduces the size of atbm_wifi significantly

**Comment by capncybo** [comment]
Nice find ;-)

**Comment by gtxaspec** [comment]
fixed in https://github.com/gtxaspec/wz_mini_hacks/commit/973cc4d8e78c1e5a857257eaa147d0434b2a13b5
