### ISSUE TITLE
Not persistant after reboot

### ISSUE THREAD

**Issue by RogueDried** [gtxaspec/wz_mini_hacks#16]
Fails to load after a soft reload either via the Wyze App or command line. Need to hard power cycle the camera to get it to operate again.

**Comment by gtxaspec** [comment]
just tested latest version...not having this issue.  Have you tried a different memory card?  works fine for me, both using the app, command line, and power cycle.

**Comment by frugala** [comment]
can confirm it works fine for me too.  I have edited the run_mmc.sh file via SSH and rebooted many times now without having to climb the ladder and touch the camera.  I can reboot either via the wyze app, or using 'reboot' via ssh.

**Comment by gtxaspec** [comment]
Let us know if this is still occurring, unable to reproduce.

**Comment by Vendo232** [comment]
Running latest ( and the only I guess ) RTSP firmware and the hack with Ethernet enabled. All works fine on first boot, connectivity via Ethernet works, but when I disconnect the cam and connect again with Ether. still enable the cam would not connect.

**Comment by gtxaspec** [comment]
disconnecting, as in removing the Ethernet and plugging it back in, or rebooting?

**Comment by Vendo232** [comment]
Edited post above

**Comment by gtxaspec** [comment]
I've observed some cards corrupt more easily than others.  keep us updated if you have more info.  

also remember whenever you remove and reinsert the sd card, you will need to reboot with this mod.

**Comment by Vendo232** [comment]
just discovered that when I left the cam running over night it was recording 24/7 on SD Card and I do not remember ever activating that in Wyze App. Strange.  So when I hot unlagged the cam it  was recording and probably corrupt some files on the SD Card. Reformatting and trying again, this time I will ensure all is disabled in Wyze APP.
