### ISSUE TITLE
Wyze Cam v3 no stream audio when loading wz_mini_hacks

### ISSUE THREAD

**Issue by mrsarge** [gtxaspec/wz_mini_hacks#161]
Brand new Wyze Cam v3.
If I boot it with the Micro SD card inserted, thus loading wz_mini_hacks, I have no audio in the Wyze app.
Also tried to enable the RTSP stream and I have no audio in there either.

Removed the Micro SD card, rebooted and audio is working properly in the Wyze app.

Firmware 4.36.9.139

**Comment by gtxaspec** [comment]
Just tested, on 139, using the latest non beta wyze app (android) sound works fine with wz_mini.  
What platform? android or ios?
latest wz_mini release?

**Comment by mrsarge** [comment]
Android.
Downloaded the master.zip yesterday.

**Comment by mrsarge** [comment]
Since everything is fine when booting without the Micro SD, the app should be ok.
I also just tested the Speak feature and it doesn't work when using wz_mini.
It's like the speaker and microphone were disabled.

(I got the audio prompt from wz_mini when I did the first boot)

**Comment by gtxaspec** [comment]
let me try a fresh install and check stand by

**Comment by gtxaspec** [comment]
confirmed, seems like some sort of regression.  looking into it now

**Comment by capncybo** [comment]
So that's why that "Rat-Bird" Magpie I tried to Scare off... never flew away. LOL

**Comment by gtxaspec** [comment]
found the issue, new release soon

**Comment by gtxaspec** [comment]
fixed in latest release, please test

**Comment by mrsarge** [comment]
It works!

Thank you for the quick fix.

**Comment by gtxaspec** [comment]
resolved for now =D
