### ISSUE TITLE
Wishlist Item: Home Assistant integration

### ISSUE THREAD

**Issue by ryny24** [gtxaspec/wz_mini_hacks#162]
Does anyone know if this is possible with the script capabilities?   Possible Person Detection as an entity. :)

I'll play around!

**Comment by Vendo232** [comment]
you can also use frigate NVR and add Wyze cams via RTSP then Frigate has amazing HA integration including selectable motion detection for person, cat, car etc..

![image](https://user-images.githubusercontent.com/44098230/181387174-46eb926e-3d75-4d5c-b89e-fd215f68928b.png)

**Comment by gtxaspec** [comment]
see above, resolving!
