### ISSUE TITLE
Branch no-conntrack/video regression

### ISSUE THREAD

**Issue by jemershaw** [gtxaspec/wz_mini_hacks#179]
I'm just wondering what the status was for the no-conntrack branch?

I think it fixed some of my connection problems  with the v3 and the latest firmware.

I think I might have ran into something similar to https://github.com/gtxaspec/wz_mini_hacks/issues/161 but with the video being a black screen in rtsp(this was using the master branch)

**Comment by gtxaspec** [comment]
@jemershaw issues even with today's latest release?

**Comment by jemershaw** [comment]
I just installed it, it usually takes a few reboots etc before the video on startup has problems.

**Comment by gtxaspec** [comment]
ok let me know, if you still have issues I will update the conntrack branch too.

**Comment by jemershaw** [comment]
Yes it looks like it is still happening on the latest master release. My guess is because I have rtsp-simple-server trying to connect once it is listening.

**Comment by gtxaspec** [comment]
@jemershaw and it only works with nocontrack?

**Comment by jemershaw** [comment]
I think it was still happening on that branch. I only ran into the audio problem in the no-conntrack branch but I didn't test that much so let me redeploy.

**Comment by jemershaw** [comment]
The video seems fine but the audio doesn't seem to want to work.

**Comment by gtxaspec** [comment]
so:
master no video
no-conntrack video ok, audio broken

**Comment by jemershaw** [comment]
@gtxaspec that is correct. This is for a V3 camera.

**Comment by gtxaspec** [comment]
and it only happens when using `rtsp-simple-server`?

**Comment by jemershaw** [comment]
I haven't been able to time it right to create a connection without rtsp-simple-server. It seems like the lastest master release over some time the rtsp session for the tcp connection loses video. Still unclear why.

**Comment by gtxaspec** [comment]
have you tried using UDP instead of TCP?

**Comment by jemershaw** [comment]
I didn't try, do you know if it is it listening by default?

**Comment by gtxaspec** [comment]
it listens on udp and tcp by default

**Comment by gtxaspec** [comment]
any update? still having issues?

**Comment by jemershaw** [comment]
I'm actually doing mapping with ffmpeg so udp doesn't work most of the time because video sometimes is corrupted.

**Comment by jemershaw** [comment]
I even tried bypassing rtsp-simple-server and just use frigate and sometimes it works and sometimes the videos don't get recorded. I had to resort to putting back on the stock rtsp version since that doesn't have any problems.

**Comment by jemershaw** [comment]
Also some of the recordings are just a black screen. I'm not sure if anyone else is using frigate and is having this problem or not.

**Comment by gtxaspec** [comment]
I would post in the discussions area for other frigate users or rtsp-simple-server users to see, and if possible share setup information to fix your issue.  resolving for now
