### ISSUE TITLE
add Buy me a Coffee button!

### ISSUE THREAD

**Issue by Vendo232** [gtxaspec/wz_mini_hacks#18]
@gtxaspec  you are doing incredible job here! Please consider adding Buy me a Coffee button to compensate your time.

**Comment by Vendo232** [comment]
.

**Comment by gtxaspec** [comment]
haha maybe.  I'd rather people thank @mnakada and @bakueikozo, the guys who did the research and development that I based my work on... they are heros!

**Comment by bakueikozo** [comment]
nice work!
