### ISSUE TITLE
PanV2:  Vertical Tilt not stable on custom kernel

### ISSUE THREAD

**Issue by gtxaspec** [gtxaspec/wz_mini_hacks#19]
Using our custom kernel, Vertical Tilt on the PANv2 is unstable...unless you have the motor speed in the app set to 9, it barely moves.  Confirmed this is not a HW issue, using the stock kernel it works fine.

Horizontal movement works fine.

Is this an I2C problem?  Need to investigate how the motor kernel module interfaces with the kernel.  The I2C settings in our kernel config match the stock config supplied by wyze...

**Comment by Grntrenchman** [comment]
Outside of the app, trying to move using "cmd move" works fine for horizontal, but hangs for vertical, and Ctrl-C leaves it in an error state (running again produces "error"..)

I'm not sure if it's possible to use the higher motor speed from here (without the app), or where it's set.

**Comment by gtxaspec** [comment]
found out that PB_27 is claimed by the kernel for MMC detect, which is not applicable to the Panv2, this should be fixed soon by a kernel patch.

Tested on a Pan v2, vertical tilt is super smooth now.

**Comment by wokawoka** [comment]
> found out that PB_27 is claimed by the kernel for MMC detect, which is not applicable to the Panv2, this should be fixed soon by a kernel patch.
> 
> Tested on a Pan v2, vertical tilt is super smooth now.

Has this problem already been resolved with the last public version of wz_mini_hacks ?
Not long ago I tried a recent version of wz_mini_hacks and I was still  experiencing the problem on my PAN V2.
Thank you!

**Comment by gtxaspec** [comment]
not feasable to fix on stock firmware; fixed in thingino

**Comment by wokawoka** [comment]
> not feasable to fix on stock firmware; fixed in thingino

thank you for your answer
