### ISSUE TITLE
V2 uBoot experiment

### ISSUE THREAD

**Issue by endertable** [gtxaspec/wz_mini_hacks#190]
@gtxaspec One of my V2 cams had a unique md5sum for /dev/mtd0, so I took your V2_kernel.bin and placed it as factory_ZMC6tiIDQN on the SD card.  Not really sure if that is the way it would work or if you have to compile that kernel file a different way for SD card, but the cam is reacting to the factory file.  Unfortunately, in this case, it is rebooting.  Would you like a copy or is that boat not worth sailing?

**Comment by gtxaspec** [comment]
@endertable 

name it `factory`
and see what happens.  

also you can analyze uboot: `dd if=/dev/mtd0 of=/opt/mtd0.bin` and then run `strings /opt/mtd0.bin | grep factory` and see if you get any output

**Comment by endertable** [comment]
Yep, I grepped 'factory' and I got: factory_ZMC6tiIDQN
I renamed it to 'factory' and it didn't start wyze_mini, just started normal but the filename above is what puts it into a reboot-loop.

I guess I should also mention, this cam does not have a wz_mini modified kernel loaded on it..

So should it just be as simple as putting your V2_kernel.bin on the SD card as factory_ZMC6tiIDQN or do those kernels have to be compiled differently to boot off the SD card?

**Comment by gtxaspec** [comment]
send me the mtd0.bin file with the md5sum and I'll test it

**Comment by gtxaspec** [comment]
@endertable to confirm, this is from a V2? what color?

**Comment by endertable** [comment]
It is a white V2 cam and i used the following command:  

dd if=/dev/mtd0 of=/tmp/mtd0

Sorry the final file I sent you was based on my script's naming convention of {Camera Name}_{MAC address}_{MD5 hash}_uBoot but it is the file from above command.  Most of my V2's uBoot have an MD5sum of b1f6f38dbb48d4e9d8911833aff0bc99

If you prefer, if you want to send me a factory_ZMC6tiIDQN, I can do the testing if you want so you don't risk bricking a cam.

Whichever way...

**Comment by gtxaspec** [comment]
just wanted to make sure =D  I have a v2 wired up with a flash chip wired up externally.   so if i need to reprogram the flash chip no big deal

**Comment by gtxaspec** [comment]
it works fine, and boot wz_mini.  i tested this by erasing /dev/mtd2, where the kernel lives on the camera.  then renaming v2_kernel.bin as the factory file, it boots it fine.  what a find!

**Comment by gtxaspec** [comment]
@endertable you don't have any PAN camera's do you? lol

**Comment by endertable** [comment]
I do, if my memory serves me they had the sane uboot md5 as the other V2’s.  I can confirm that when I get back to my server.

**Comment by endertable** [comment]
yes, the pancam V1 have the same md5sum as most of the V2's:  b1f6f38dbb48d4e9d8911833aff0bc99

**Comment by gtxaspec** [comment]
nice.  now we just need someone to be a guinea-pig and test flash the bootloader on the pan... sadly I don't have one anymore I borrowed the ones I used to test

**Comment by endertable** [comment]
So I imagine you are using the flasheraseall commands?  What exact commands did you use to put the boot onto mtd0?

**Comment by gtxaspec** [comment]
just

`flashcp -v file.bin /dev/mtd0`

no need to do flash erase all.  flashcp does the erase.

**Comment by endertable** [comment]
Ok, I did it to Pancam and rebooted and I verified it took by doing an md5sum on a dd out.  So at minimum I know it works with the stock firmware so no reason it shouldn't work with the factory file.  This cam also has a V1 sensor on it's back and I just got back from doing stuff and am on my way out to go do stuff so when I get back later I can test it with wz-mini boot.

**Comment by endertable** [comment]
Strangest thing, is that the cam that I got the uBoot off of reacts to the factory file but it goes into a boot-loop.  The yellow light goes off for a second then comes on to reboot.   Sometimes it will just go on to boot the stock FW kernel on mtd2, but it absolutely refuses to boot wz_mini.  I used the same SD card on other V2's after I reflashed their uBoot and no issue, just the one cam.  No logs created or nothing.  

Very strange

**Comment by gtxaspec** [comment]
wierd I put it on all the v2s I have tomorrow and test.  can you access the serial console on the one that doesn't work (if you have the ability to)?

**Comment by endertable** [comment]
Doing serial console access As always sounded interesting. I’m sure there are tutorials out there. Do you have some links to some? Or do you have your own tutorial and software/parts list?

**Comment by gtxaspec** [comment]
do you have a raspberry pi? it's the simplest solution if you do... otherwise I can whip up a tutorial with photos

**Comment by endertable** [comment]
I do have a raspberry pi.

**Comment by gtxaspec** [comment]
![20220722_205322.jpg](https://user-images.githubusercontent.com/12115272/180589558-b500070d-e5d4-4eca-9fb3-0e3675a99b9b.jpg)

**Comment by endertable** [comment]
Ok.  Did you solder or purchase some special clip pins.  And you use a special getty from pi or telnet to cam or is it a kermit proggy?

**Comment by gtxaspec** [comment]
you can use something like these:
https://www.amazon.com/Connector-Arduino-Raspberry-Including-Headers/dp/B0815S6P8Y
you really don't have to solder the headers on,  use the male to female ones, and just poke them through while you are reading the terminal

you can use `tio` on the rpi to connect.  enable serial console in raspi-config

**Comment by endertable** [comment]
Sweet!!  Part on order. You requested the output of uBoot.  Do I redirect output of tio to file or does it have an auto capture log file.  I am new this particular stuff but it sounds fun. 😀

**Comment by endertable** [comment]
![B4D2BDA3-7BB9-4D42-9CA0-B03E0E498FA9](https://user-images.githubusercontent.com/75660899/182424402-27da86f6-cfd0-4bfc-849b-68769b38db5d.jpeg)

looks like they may have changed the hardware.  Mine looks different.   But i believe those are the UART pons/holes on the lower left of the main board?  One is a squarez

**Comment by gtxaspec** [comment]
yes, those look like the serial pins.

**Comment by endertable** [comment]
OK, I connected all pins to pi pins (6,8,10) and to the 3 holes, executed:   tio -b 115200 /dev/serial0  then plugged in cam.
Nada.  One of the holes has a square around it and in one schematic that was for 3.3v but then where would the ground be?!?

Another guy stated from left to right GND, TX, RX.  Is there a way to test which one is ground cuz I am surprised I haven't fried this yet, hehe.

**Comment by endertable** [comment]
Here is the log from the ?new? V2 that had the uBoot.  You can see the reboot call in there that creates the boot loop.

[tio1.log](https://github.com/gtxaspec/wz_mini_hacks/files/9247192/tio1.log)

**Comment by gtxaspec** [comment]
can you pull the card, is there a log file called something initramfs.log on the root of the sd card

**Comment by endertable** [comment]
There was no such file anywhere on the SD card.  Or any other new file for that matter..

**Comment by gtxaspec** [comment]
can you try formatting the sd card and doing a fresh install? or using another sd card if you have it preferably.

it may be an error loading files from the  sdcard

**Comment by gtxaspec** [comment]
any update? @endertable

**Comment by endertable** [comment]
Sorry I forgot to post, yes it must have been the card.  I actually just reformatted the same card and it worked...
