### ISSUE TITLE
Wyze kernel update

### ISSUE THREAD

**Issue by endertable** [gtxaspec/wz_mini_hacks#22]
Wyze just released a new update just for the cam V3 (4.36.9.131) and I noticed the kernel was actually updated in this release.  It hasn't been updated in at least the last 6 releases.  With that, I know this MOD is using it's own kernel, so it's more of a question I would have then so much an issue:  

Should we allow the latest update, or is there a risk that the updated Wyze binaries may fault or not work as desired without the proper kernel?  Should we wait for an updated factory_t31_ file?

For the first time, I noticed a change in memory and not sure of what significance that may have:

mem=96M@0x0 rmem=32M@0x6000000 to
mem=99M@0x0 rmem=29M@0x6300000

**Comment by gtxaspec** [comment]
the kernel is taken from the t31 sdk,so it really doesn't change unless the sdk is updated which I haven't seen a new version of so far, most likely they have updated some driver that is complled into the kernel. 

the apps should work regardless of kernel version, as long as the right drivers and the command line memory mappings aren't too far off from the stock values.

I will check the kernel command lines of the latest version and update accordingly, thanks for the info.
