### ISSUE TITLE
usb-storage devices don't work, no support in kernel

### ISSUE THREAD

**Issue by gtxaspec** [gtxaspec/wz_mini_hacks#24]
usb-storage is missing from kernel, unable to use USB flash drives/ssd/hdd as storage.  
need to include usb-storage, probably scsi subsystem too.

**Comment by capncybo** [comment]
In your opinion...
is adding "usb-storage"  going to be Difficult or Very time consuming to implement?
Or do you think it should be doable & well within your current knowledge-level & existing skill-set?

**Comment by gtxaspec** [comment]
it's already done, lol.  I'll have an updates release within the day.

**Comment by capncybo** [comment]
OMG, wow.  Your answer certainly exceeded my expectations... Very impressive,  Looking forward to your update.
And Hopefully, Many many more,
Awesome work!!!

**Comment by gtxaspec** [comment]
new version including support now released.

**Comment by capncybo** [comment]
Just Flashed the NEW version... Super Job!!!
IMO The audio playback is a really professional addition.
+
It worked 1st attempt even though I decided to try my BIGGER 128G SD-CARD.
Awesome stuff,
Thx & keep up the Jaw Dropping Work ;-)
