### ISSUE TITLE
MQTT?

### ISSUE THREAD

**Issue by guarddog13** [gtxaspec/wz_mini_hacks#247]
Any Chance you could add MQTT support? I'm not sure if that would even be possible lol.

**Comment by virmaior** [comment]
Discussion ongoing at https://github.com/gtxaspec/wz_mini_hacks/discussions/75
and https://github.com/gtxaspec/wz_mini_hacks/issues/171 was opened by ... guarddog13

**Comment by gtxaspec** [comment]
see mentioned issues.
