### ISSUE TITLE
USB OTG Doesn't power HL_PANv2... solved.

### ISSUE THREAD

**Issue by gtxaspec** [gtxaspec/wz_mini_hacks#25]
Curiously, using a USB OTG adapter or micro usb hub, doesn't power the PanV2 at all.  

Inspecting the unit inside, the connector has 5 wires coming from the base to the board.  if the ID pin is shorted for OTG, could this be preventing the camera from booting?

**Comment by gtxaspec** [comment]
Looks like I was right!  Removing the ID pin does allow the USB OTG cable / adapter / hub to power the device.  The USB devices work too!

If you have a PANv2 and you want to use USB OTG, for a HUB, flash drive, ethernet adapter or whatever, see the attached photos.

You need to remove the 2nd red cable from the connector, or just snip it and tape the ends off.  It is not needed.

**Comment by gtxaspec** [comment]
![img1](https://user-images.githubusercontent.com/12115272/166132631-072b5627-958d-44da-abc8-09d03a478506.jpg)
![img2](https://user-images.githubusercontent.com/12115272/166132632-1ee93d4e-3630-49d9-818d-a366c7991646.jpg)

**Comment by capncybo** [comment]
Thank you for sharing this information, this makes me really ant to purchase one.
