### ISSUE TITLE
Spotty connection to my NAS server 

### ISSUE THREAD

**Issue by IpslWon** [gtxaspec/wz_mini_hacks#274]
I've set up a v3 Wyze Cam Indoor/Outdoor and have it connected as a general RTSP stream camera in my QNAP server. The camera wont stay connected. I can connect to the web GUI and it seems to be working, but the camera itself will drop it's connection. The camera is relatively close to the WiFi AP so I don't think that's an issue. 

I've tried changing RTSP_HI_RES_ENC_PARAMETER to 2, 4, 8 without change. Any direction would be appreciated.

**Comment by gtxaspec** [comment]
please try the latest release with go2rtc rtsp server, many performance issues have been resolved.  
please re-open if opportunities persist.
