### ISSUE TITLE
pan v2 bootloader image?

### ISSUE THREAD

**Issue by HclX** [gtxaspec/wz_mini_hacks#275]
I see this hack works for pan v2, can you help me dump the flash content of pan v2 using this hack? I'm studying it's factory reset image format and it seems encrypted. Trying to figure it's encryption method and decryption key but I will need a copy of the bootload image.

**Comment by gtxaspec** [comment]
[mtd0.bin.gz](https://github.com/gtxaspec/wz_mini_hacks/files/9399840/mtd0.bin.gz)
@HclX

**Comment by gtxaspec** [comment]
@HclX did that work for you? Let me know if you need anything else.
