### ISSUE TITLE
Reboot loop when using web config reboot

### ISSUE THREAD

**Issue by haderp** [gtxaspec/wz_mini_hacks#276]
When using the reboot option after configuration change the camera will enter a reboot loop after the 90 second wait time due to the reload function calling document.location.reload calling the reboot command directly from the url.  Would location.replace and redirecting back to config.cgi be a better option?

**Comment by virmaior** [comment]
yes, will fix.

**Comment by gtxaspec** [comment]
@haderp can you confirm this is fixed?

**Comment by haderp** [comment]
Yes, can confirm the reboot function now works as expected and this issue is resolved.
