### ISSUE TITLE
Scripts timeout? 

### ISSUE THREAD

**Issue by guarddog13** [gtxaspec/wz_mini_hacks#280]
At least once a day I have to reboot one of my 7 cameras as the waitmotion scripts I have in rc.local.d quit working. The cameras work fine with no disconnects. I'm not sure why the scripts are dying out periodically and it's only happening overnight btw.

**Comment by gtxaspec** [comment]
can you share your scripts? maybe we can debug them.

**Comment by guarddog13** [comment]
I'm not home to be able to copy it proper. I have it in discussion #261 the only thing different is i have done 2 second sleeps and added some more curl commands.
