### ISSUE TITLE
Crontab Not Working

### ISSUE THREAD

**Issue by guarddog13** [gtxaspec/wz_mini_hacks#282]
I have crontab enabled on my cameras and if I try command crontab -e I get the following error. 

"crontab: can't change directory to '/var/spool/cron/crontabs': No such file or directory"

**Comment by gtxaspec** [comment]
the command you want to use is:

`crontab -c /opt/wz_mini/etc/cron -e`

**Comment by guarddog13** [comment]
Thank you so much!!

**Comment by gtxaspec** [comment]
see solution, closing!
