### ISSUE TITLE
[FEATURE REQUEST] Set static / preferred IP

### ISSUE THREAD

**Issue by C2BB** [gtxaspec/wz_mini_hacks#285]
Thank you for this wonderful solution, it was exactly what I needed to solve my RTSP issues in Home Assistant. In my setup I use an add-on to host a separate wifi network and it lacks the option to do any ip/mac binding. Is that something that could be easily incorporated into this handy little bag of tricks? If not a static IP perhaps a preferred IP or range and fallback to whatever DHCP offers if there is a conflict?

**Comment by claudobahn** [comment]
This is something you typically configure on your router. The router's DHCP server is responsible for assigning IP addresses, so typically you just grab the MAC address off your camera and ear-mark it for a particular IP address on your router.

**Comment by C2BB** [comment]
Typically, yes, but in my setup i'm creating a wireless network for all my IoT devices through a home assistant add-on that does not offer the ability of manual assignment/binding through its included DHCP server, so I figured I'd throw this out there in the off chance it's a simple feature addition.

**Comment by C2BB** [comment]
> This is something you typically configure on your router. The router's DHCP server is responsible for assigning IP addresses, so typically you just grab the MAC address off your camera and ear-mark it for a particular IP address on your router.

Typically, yes, but in my setup i'm using a USB wifi adapter to create wireless network for all my IoT devices through a home assistant add-on that does not offer the ability of manual assignment/binding through its included DHCP server, so I figured I'd throw this out there in the off chance it's a simple feature addition.

**Comment by bjs-pdx** [comment]
`a home assistant add-on that does not offer the ability of manual assignment/binding through its included DHCP server,`

Which add-on?  Almost every DHCP server has the ability to create reserved IP addresses.

**Comment by C2BB** [comment]
> `a home assistant add-on that does not offer the ability of manual assignment/binding through its included DHCP server,`
> 
> Which add-on? Almost every DHCP server has the ability to create reserved IP addresses.

https://github.com/joaofl/hassio-addons/tree/master/hassio-hotspot

**Comment by bjs-pdx** [comment]
Did you have to install this to make it work:

https://github.com/home-assistant/addons/blob/master/dhcp_server/README.md

If so: 

`This add-on provides a simple DHCP server for your network. It provides some basic needs, like, reserving IP addresses for your devices to ensure they always get assigned the same IP address.`

**Comment by C2BB** [comment]
> Did you have to install this to make it work:
> 
> 
> 
> https://github.com/home-assistant/addons/blob/master/dhcp_server/README.md
> 
> 
> 
> If so: 
> 
> 
> 
> `This add-on provides a simple DHCP server for your network. It provides some basic needs, like, reserving IP addresses for your devices to ensure they always get assigned the same IP address.`
> 
> 
> 
> Try this page (specifically HOSTS option):
> 
> 
> 
> https://github.com/home-assistant/addons/blob/master/dhcp_server/DOCS.md

Nope, just added the repo to my add-in's custom repos list, installed from the web gui and was up and running with this cheap usb dongle https://a.co/d/edu81Qi . It's been working great for my WiFi based smart bulbs and switches. Brought my wyze cams into the mix the other day and while they work as well, a restart of HA / host leaves me having to chase down IPs and update my frigate configurations every time.

**Comment by claudobahn** [comment]
It looks like the https://github.com/joaofl/hassio-addons/tree/master/hassio-hotspot add-on uses udhcp, there's a udhcp.conf file included with that plugin. From the documentation for udhcp, all you have to do is add
```
static_lease 00:60:08:11:CE:4E 192.168.0.54
```
to that included udhcp.conf file. Obviously replace MAC/IP.

**Comment by C2BB** [comment]
> It looks like the https://github.com/joaofl/hassio-addons/tree/master/hassio-hotspot add-on uses udhcp, there's a udhcp.conf file included with that plugin. From the documentation for udhcp, all you have to do is add
> 
> ```
> static_lease 00:60:08:11:CE:4E 192.168.0.54
> ```
> 
> to that included udhcp.conf file. Obviously replace MAC/IP.

Thank you for the lead, I'll give that a go.

**Comment by C2BB** [comment]
Worked like a charm. Thank you @claudobahn !!!

**Comment by bjs-pdx** [comment]
If you are satisfied with the solution, you should close this.
