### ISSUE TITLE
Camera will not boot with wz_mini_hacks

### ISSUE THREAD

**Issue by brentfraser** [gtxaspec/wz_mini_hacks#31]
First of all, thanks for the great project!  I have a new Wyze Cam v3 (MAC D0:3F:27:xx:xx:xx), but it will not boot with wz_mini_hacks (commit 26af3aa). It shows the red light for 5 seconds then blinks, shows the red light etc.

I used a16 GB microsd card, formatted fat32, 
- added the content of SD_ROOT so the root of the card contains
```
    wz_mini (folder)
    factory_t31_ZMC6tiIDQN
```
- set RTSP_ENABLED="true" in run_mmc.sh
- turned off the camera, inserted the microSD card, turned on camera

but it just does the red light , blink 5 second cycle.  After 10 minutes, I turned it off.

Am I missing something?   Thanks!

**Comment by brentfraser** [comment]
It seems Windows 10 was the problem.  I had formatted the micro SD card on Windows 10 (as fat32).  After the camera boot problem, I moved the micro SD card on to an Ubuntu machine and deleted all the files (including the pesky "System Volume Information" folder).  Then using Ubuntu I copied the SD_ROOT contents on to the sd card.  

The camera now boots!

**Comment by brentfraser** [comment]
It works great!  I've tested the RTSP stream with clients on Windows (VLC), Ubuntu (VLC, ffplay), and on a QNAP NAS.  All good.

**Comment by gtxaspec** [comment]
great to hear!

**Comment by crossan007** [comment]
I had the same experience.  Windows 10 prepared SD card caused my V3 camera to go into a "red light" boot loop.

Preparing the SD Card using a raspberry pi seems to have created a usable wz_mini_hacks card 😎 

> It seems Windows 10 was the problem. I had formatted the micro SD card on Windows 10 (as fat32). After the camera boot problem, I moved the micro SD card on to an Ubuntu machine and deleted all the files (including the pesky "System Volume Information" folder). Then using Ubuntu I copied the SD_ROOT contents on to the sd card.
> 
> The camera now boots!

**Comment by zsmitchell** [comment]
For anybody else that is struggling with this...what worked for me was formatting my SD card OUTSIDE of windows (I used the download from SDCARD.org) and it booted right up after that.
