### ISSUE TITLE
After upgrade, existing "root" cron file is copied to /opt/wz_mini/etc/cron/cron instead of /opt/wz_mini/etc/cron

### ISSUE THREAD

**Issue by KevinKadow** [gtxaspec/wz_mini_hacks#333]
After running "upgrade-run.sh", the "root' cron file is one folder deeper than it should be, is in /opt/wz_mini/etc/cron/cron/root

**Comment by kohrar** [comment]
I see the same issue as well. Should be fixed by #337.

**Comment by kohrar** [comment]
@gtxaspec has merged #337. Can you confirm if this is fixed by re-running the upgrade script again and close the issue if it's resolved? Thanks!

**Comment by capncybo** [comment]
@KevinKadow & @kohrar I just upgraded a WYZE v3... Seems to be working perfectly now. 
Thanks for the PR & for the merge Gentlemen.

**Comment by gtxaspec** [comment]
resolved
