### ISSUE TITLE
V2 compatibility 

### ISSUE THREAD

**Issue by gtxaspec** [gtxaspec/wz_mini_hacks#34]
uboot sources support loading kernel factory file, but is disabled on production models.

also, compiling uboot from source doesn't boot on camera, need to reflash via spi programmer.

hmm... has anyone compiled uboot successfully for the v2?

**Comment by endertable** [comment]
You may have already seen this and it might not offer you anything but I just want to make sure since he dealt mostly with the V2:

https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/blob/master/hacks/flashinguboot.md

**Comment by gtxaspec** [comment]
yep thats the one I tried, and the one that bricked my camera.  Luckily I have the tools and know how to repair =D

**Comment by endertable** [comment]
I remember you asking @BiatuAutMiahn or was his project specific to the V3 only?

**Comment by gtxaspec** [comment]
v3 only, still looking for someone that has a working v2 bootloader from dafang

**Comment by gtxaspec** [comment]
kernel compiled OK, tested good.  right now installation would have to reflash the camera, so not as easy as the V3s.  If we had a working u-boot, flash once and then boot from the sd card.

**Comment by gtxaspec** [comment]
latest release includes v2 support.

**Comment by endertable** [comment]
Fantastic work!!  Thanks for all your efforts!
