### ISSUE TITLE
RTSP - low bitrate

### ISSUE THREAD

**Issue by gtxaspec** [gtxaspec/wz_mini_hacks#35]
researching

**Comment by gtxaspec** [comment]
@vendo232 what are you using to measure the bitrate?

**Comment by gtxaspec** [comment]
Can you try to `ffmpeg -i <file` to compare between RTSP fw and wz_mini?

this is what i show from wz_mini:

```
  Duration: 00:01:00.05, start: 0.000000, bitrate: 1059 kb/s
  Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080, 927 kb/s, 20 fps, 20 tbr, 1200k tbn, 40 tbc (default)
```

**Comment by gtxaspec** [comment]
there may be a bug in the v4l2rtspserver when audio is enabled the bitrate is much lower and lots of stream errors, at least for me.

i will try to recompile, and also test a different version of the rtspserver.

**Comment by gtxaspec** [comment]
this is fixed now

**Comment by Vendo232** [comment]
> Can you try to `ffmpeg -i <file>` to compare between RTSP fw and wz_mini?
> 
> this is what i show from wz_mini:
> 
> ```
> Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'test.mp4':
>   Metadata:
>     major_brand     : isom
>     minor_version   : 512
>     compatible_brands: isomiso2avc1mp41
>     title           : LIVE555 Streaming Media v2022.04.15
>     encoder         : Lavf58.76.100
>     comment         : LIVE555 Streaming Media v2022.04.15
>   Duration: 00:00:34.06, start: 0.000000, bitrate: 982 kb/s
>   Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080, 980 kb/s, 19.99 fps, 20 tbr, 90k tbn, 40 tbc (default)
>     Metadata:
>       handler_name    : VideoHandler
>       vendor_id       : [0][0][0][0]
> ```
> 
> you can use the command `ffmpeg -i rtsp://user:pass@ip:8554/unicast -acodec copy -vcodec copy test.mp4` to record

here is the RTSP WZ HACK file

' ffmpeg version 2022-05-12-git-30e2bb0f64-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.3.0 (Rev1, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      57. 24.101 / 57. 24.101
  libavcodec     59. 28.100 / 59. 28.100
  libavformat    59. 23.100 / 59. 23.100
  libavdevice    59.  6.100 / 59.  6.100
  libavfilter     8. 38.100 /  8. 38.100
  libswscale      6.  6.100 /  6.  6.100
  libswresample   4.  6.100 /  4.  6.100
  libpostproc    56.  5.100 / 56.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'b.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.45.100
  Duration: 00:02:26.03, start: 0.000000, bitrate: 287 kb/s
  Stream #0:0[0x1](und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080, 285 kb/s, 20 fps, 20 tbr, 10240 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0] '

and here is from wyze rtsp fw

' ffmpeg version 2022-05-12-git-30e2bb0f64-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 11.3.0 (Rev1, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      57. 24.101 / 57. 24.101
  libavcodec     59. 28.100 / 59. 28.100
  libavformat    59. 23.100 / 59. 23.100
  libavdevice    59.  6.100 / 59.  6.100
  libavfilter     8. 38.100 /  8. 38.100
  libswscale      6.  6.100 /  6.  6.100
  libswresample   4.  6.100 /  4.  6.100
  libpostproc    56.  5.100 / 56.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'b.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.45.100
  Duration: 00:02:26.03, start: 0.000000, bitrate: 287 kb/s
  Stream #0:0[0x1](und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080, 285 kb/s, 20 fps, 20 tbr, 10240 tbn (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0] '

**Comment by Vendo232** [comment]
you can achieve the same in VLC player

![image](https://user-images.githubusercontent.com/44098230/168441478-42c2156e-343d-43aa-811b-ead64ac55008.png)

**Comment by Vendo232** [comment]
I`m going to test the new version today

**Comment by gtxaspec** [comment]
@Vendo232 can you test something for me on your existing install?

**Comment by Vendo232** [comment]
If course

**Comment by gtxaspec** [comment]
open up vlc and start watching the stream, then connect with ssh, and run the following commands on the camera:

```
/system/bin/impdbg --enc_rc_s 0:48:4:2048
/system/bin/impdbg --enc_rc_s 0:52:4:2048
```

**Comment by Vendo232** [comment]
should I look for bitrate?

**Comment by gtxaspec** [comment]
look at the general image quality and see if it is ok for you compared to stock rtsp and anything else

**Comment by gtxaspec** [comment]
you can raise the 2048 number up to 8096 if you want

**Comment by Vendo232** [comment]
what is the difference between command with 48 and 52? should they be executed toghether everytime?

**Comment by gtxaspec** [comment]
first one is average and second is max bitrate

**Comment by Vendo232** [comment]
I`m running the RTSP FW + mini RTSP and the cam is very slow.

**Comment by gtxaspec** [comment]
Oh, i see, yes you are running 2 servers it will slow down since the quality goes down.  try stopping one, and run the commands and see if your quality goes up

**Comment by gtxaspec** [comment]
(the image quality should be identical between the two servers anyway)

**Comment by gtxaspec** [comment]
![win1](https://user-images.githubusercontent.com/12115272/168452585-be083422-7803-4c32-837f-3bc6e1f5f7f0.png)

**Comment by gtxaspec** [comment]
![win1](https://user-images.githubusercontent.com/12115272/168452597-40662d16-e15e-413b-8d5c-1e6f1472b243.png)

**Comment by gtxaspec** [comment]
![win1](https://user-images.githubusercontent.com/12115272/168452614-170287c0-2995-4c85-b55f-9eefb6367602.png)

**Comment by gtxaspec** [comment]
![win1](https://user-images.githubusercontent.com/12115272/168452687-7016c5ce-9aa4-4750-9582-9c398284bac2.png)

**Comment by Vendo232** [comment]
trying 8096 on both, it is looking really good

![image](https://user-images.githubusercontent.com/44098230/168452762-d946d3f9-3fd5-4c1b-932c-f7bd2c0fc0d7.png)

**Comment by gtxaspec** [comment]
nice.  i will issue a new release soon
