### ISSUE TITLE
Wyze V3 Firmware 4.36.0.88 wlan0 not found

### ISSUE THREAD

**Issue by foureight84** [gtxaspec/wz_mini_hacks#361]
I loaded a 32GB FAT 32 SD with the content of "SD_ROOT", and inserted the SD card into the Wyze Cam V3 (firmware  4.36.0.88). I can hear the voice prompt that "WZ Mini initializing first boot. Extracting the first swap, please wait." I wait a good 15 minutes but I don't see the camera connect to WIFI and the LED light stays red. 

This camera has been paired with my Wyze account once before and I put it away so the firmware was never updated. This was one of the first batches that shipped from Wyze when the V3 launched.

Some more info (excerpts from the wz_init.log) is below. Looks like wlan0 is not availabe. Could this version of the V3 have a different wireless chip?  Or does it need to be updated to a certain firmware in order for the hacks to work?

```
#####S10kmod#####
Enable 8189fs
Enable atbm603x_wifi_sdio
#####S11configbackup#####

....

 __________________________________
|                                  |
|                                  |
|                                  |
|                                  |
| _   _             _           _  |
|| | | |_   _  __ _| |     __ _(_) |
|| |_| | | | |/ _| | |  _ / _| | | |
||  _  | |_| | (_| | |_| | (_| | | |
||_| |_|\__,_|\__,_|_____|\__,_|_| |
|                                  |
|                                  |
|_____2020_WYZE_CAM_V3_@HUALAI_____|

+ export 'PATH=/bin:/sbin:/usr/bin:/usr/sbin:/opt/wz_mini/bin'
+ export 'PATH=/system/bin:/bin:/sbin:/usr/bin:/usr/sbin:/opt/wz_mini/bin'
+ export 'LD_LIBRARY_PATH=/system/lib:/opt/wz_mini/lib'
+ export 'LD_LIBRARY_PATH=/thirdlib:/system/lib:/opt/wz_mini/lib'
+ ifconfig lo up
+ mount -t squashfs /dev/mtdblock3 /system
mount: mounting /dev/mtdblock3 on /system failed: Resource busy
+ mount -t jffs2 /dev/mtdblock6 /configs
+ /opt/wz_mini/etc/rc.d/K03rcd
+ /opt/wz_mini/etc/rc.d/K01network
#####S01swap#####
ifconfig: wlan0: error fetching interface information: Device not found
K01network: Network HW not ready yet, try again in 5 seconds
[INFO]        : Playing the audio /opt/wz_mini/usr/share/audio/swap.wav file.
[INFO]        : Volume is set to 50.
Swap archive present, extracting
ifconfig: wlan0: error fetching interface information: Device not found
K01network: Network HW not ready yet, try again in 5 seconds
ifconfig: wlan0: error fetching interface information: Device not found
K01network: Network HW not ready yet, try again in 5 seconds
ifconfig: wlan0: error fetching interface information: Device not found
K01network: Network HW not ready yet, try again in 5 seconds
Setting up swapspace version 1, size = 134213632 bytes
UUID=1fa255eb-50d4-47bd-9508-a009a2b502db
Swap file found, enable
#####S03ethernet#####
USB Ethernet disabled
#####S04usbdirect#####
USB Direct disabled
USB RNDIS disabled
No alternate iface enabled
#####S10firmware#####
Firmwware updates enabled, monitor script running
S09coredump: wpa_supplicant not initialized yet, try again in 5 seconds
#####S14nightdrop#####
#####S17motor#####
Motor enabled
#####S18fps#####
Seting system FPS if greater than default
sh: 20: unknown operand
sh: 20: unknown operand
+ /opt/wz_mini/tmp/.storage/app_init.sh
ifconfig: wlan0: error fetching interface information: Device not found
K01network: Network HW not ready yet, try again in 5 seconds
===========welcome to ver-comp tool=========
[ver-comp]dbg: appver:  4.36.0.88
[ver-comp]dbg: rootver: 4.36.0.56
[ver-comp]exec cmd: cp -rf /system/bin/app.ver /configs/

....

[1231 17:00:31.668][A][iCam][product_config.c:308][PRODUCT] [PRODUCT_TYPE ] [camera]   
[1231 17:00:31.668][A][iCam][product_config.c:308][PRODUCT] [PRODUCT_MODEL] [WYZE_CAKP2JFUS]   
[1231 17:00:31.668][A][iCam][product_config.c:308][PRODUCT] [BOARD_TEST   ] [0FFF]   
[1231 17:00:31.669][A][iCam][product_config.c:308][PRODUCT] [FACTORY_TEST ] [0000]   
[1231 17:00:31.669][A][iCam][product_config.c:308][PRODUCT] [HARDWARE_VER ] [T00A0000]  

....

fconfig: wlan0: error fetching interface information: Device not found
K01network: Network HW not ready yet, try again in 5 seconds
S09coredump: wpa_supplicant not initialized yet, try again in 5 seconds
ifconfig: wlan0: error fetching interface information: Device not found
K01network: Network HW not ready yet, try again in 5 seconds
S09coredump: wpa_supplicant not initialized yet, try again in 5 seconds
ifconfig: wlan0: error fetching interface information: Device not found
K01network: Network HW not ready yet, try again in 5 seconds
[watchdog]dbg:[time:46] success wdgMsgId:98307 IPC_module_get_wdg_msg_id:98307
S09coredump: wpa_supplicant not initialized yet, try again in 5 seconds
ifconfig: wlan0: error fetching interface information: Device not found
K01network: Network HW not ready yet, try again in 5 seconds
S09coredump: wpa_supplicant not initialized yet, try again in 5 seconds
ifconfig: wlan0: error fetching interface information: Device not found
K01network: Network HW not ready yet, try again in 5 seconds
S09coredump: wpa_supplicant not initialized yet, try again in 5 seconds
ifconfig: wlan0: error fetching interface information: Device not found
K01network: Network HW not ready yet, try again in 5 seconds
[watchdog]dbg:[time:61] success wdgMsgId:98307 IPC_module_get_wdg_msg_id:98307
```

**Comment by kohrar** [comment]
4.36.0.88 is pretty old. That's one of the first firmware for the v3. We're now at 4.36.9.139. Can you try upgrading it to something a bit newer and see if that helps?

You can find the official versions from Wyze Lab at:
- https://support.wyze.com/hc/en-us/articles/360024852172-Release-Notes-Firmware

If you need a particular version, I have some saved in my repo:
- https://github.com/kohrar/Wyze-Firmwares/tree/master/v3

**Comment by foureight84** [comment]
Sweet! Thank you for that. Updated to 4.36.3.18. For some reason, the sd card method wouldn't work with demo_wcv3.bin or demo.bin.

I have the conf set DISABLE_FW_UPGRADE="true". On a curious note, it's always possible to downgrade firmware right? There hasn't been a lockdown firmware to prevent downgrades?

**Comment by kohrar** [comment]
As far as I know, you should be able to downgrade using one of the older firmware files in the repo using the SD card method.

Just make sure that your SD card is FAT formatted and the firmware file is named demo_wcv3.bin. You also need to hold the SETUP button as you're powering on the camera.

**Comment by foureight84** [comment]
> As far as I know, you should be able to downgrade using one of the older firmware files in the repo using the SD card method.
> 
> Just make sure that your SD card is FAT formatted and the firmware file is named demo_wcv3.bin. You also need to hold the SETUP button as you're powering on the camera.

Thank you! I had it on FAT32... no wonder.

**Comment by kohrar** [comment]
FAT32 should work. 

It looks like there's a new firmware version out. Don't use 4.36.10.2700 as it isn't supported (yet?).

**Comment by foureight84** [comment]
Yea. I am on 4.36.3.18 since that's what was on my wyze app and it's not the latest unsupported firmware. I don't need any of the new features since I'll be using the wyze v3 with frigate. I just needed the wz mini hacks for rtsp.

**Comment by foureight84** [comment]
> FAT32 should work.
> 
> It looks like there's a new firmware version out. Don't use 4.36.10.2700 as it isn't supported (yet?).

This is quite strange. I am currently on 4.36.3.19 and which was updated using the Wyze App. The newer firmware does not show up on the app and it thinks this is the latest version. I assume it's because it's on a fetch cycle. 

I went back trying to update the firmware manually to 4.36.9.139, which is the latest that's still compatible with the wz_mini_hacks. However, no matter how many times I boot up the device with the SETUP button held down, it doesn't flash the bin file on the SD CARD and goes into setup mode.

The SD Card is 128MB in size (I've tried with a 32GB card as well). I formatted to FAT, then tried FAT32, then tried exFAT. demo_wcv3.bin is sitting on the card's root. I've even tried formatting the card via the Wyze App to no avail. Not sure what's going on.

**Comment by kohrar** [comment]
Could you try doing smaller version jumps with your upgrades? Maybe try upgrading from 4.36.3.19 to 4.36.6.17 and see if that works.

**Comment by foureight84** [comment]
> Could you try doing smaller version jumps with your upgrades? Maybe try upgrading from 4.36.3.19 to 4.36.6.17 and see if that works.

I've just tried that as well. Still the same issue. I'm seeing reports from several people on Reddit and Wyze forums that it doesn't seem to like certain SD Card brands. Though I've tried Sandisk, Samsung, PNY, and now generic.

**Comment by foureight84** [comment]
It looks like they recommend class 10 sd cards which is the specs on their branded sd cards. Apparently, I don't have any class 10 sd cards on hand funny enough. I bought some and should arrive tomorrow. If that doesn't work, I will go as far as buying one of their branded sd card to try.

**Comment by foureight84** [comment]
The Class 10 SD cards work. I guess that's a requirement as well for flashing. 32GB or less, FAT32, Class 10.
