### ISSUE TITLE
Add Basic Auth to wz_mini_hacks Web Server portal

### ISSUE THREAD

**Issue by glessa1** [gtxaspec/wz_mini_hacks#385]
Add Basic Auth to wz_mini_hacks Web Server portal

**Comment by glessa1** [comment]
I have it implemented in my clone. I can share the updates if you'd like to see them.

**Comment by virmaior** [comment]
can you do it a fork and put in a pull request?

**Comment by glessa1** [comment]
@virmaior 
Done :)

**Comment by virmaior** [comment]
nice! 
I didn't know the httpd implementation we have from busybox could even support basic auth.

**Comment by gtxaspec** [comment]
added in latest master
