### ISSUE TITLE
Work with V3 attached to flood light

### ISSUE THREAD

**Issue by ragenhe** [gtxaspec/wz_mini_hacks#392]
It appears that running wmh on a V3 that has the flood light setup (accessory) will prevent the accessory from working correctly.

I don't care if wmh cannot manage the accessory, but it would be nice if it wouldn't block the accessory from working, if at all possible.

**Comment by carzine** [comment]
I also have the same issue.

**Comment by bberg115** [comment]
Appears to be working for me and I didn't setup the spotlight in the conf file. I was successful at changing the brightness and the sensitivity. I used some of the info [here ](https://github.com/gtxaspec/wz_mini_hacks/discussions/309)to make changes.

![image](https://user-images.githubusercontent.com/17869135/218119176-a3ba5734-86b8-4d96-923e-77abc0926934.png)

**Comment by bberg115** [comment]
Stopped having access for some reason... 
![chrome_SzzYdAatZU](https://user-images.githubusercontent.com/17869135/220154679-e815be20-c810-4ffb-9d03-9f7cb87a050d.png)

**Comment by gtxaspec** [comment]
Development continued in #172
