### ISSUE TITLE
v3 pro support?

### ISSUE THREAD

**Issue by maxfield-allison** [gtxaspec/wz_mini_hacks#397]
any chance we'll see v3 pro support?

**Comment by DAMAGEDatheCORE** [comment]
This isn't an issue. Head to the discussion tab to read posts about the investigatory work already going on with the v3 Pro.

**Comment by baudev** [comment]
See https://github.com/gtxaspec/wz_mini_hacks/discussions/366

**Comment by maxfield-allison** [comment]
forgot discussions existed, sorry
