### ISSUE TITLE
RTSP - modify libcallback to inject both streams, 1080p and 360p

### ISSUE THREAD

**Issue by gtxaspec** [gtxaspec/wz_mini_hacks#40]
hook the callback's to each stream, 
```
Apr 15 00:04:43 iCamera: enc func injection save video_encode_cb=0x48b59c
Apr 15 00:04:43 iCamera: enc func injection save video_encode_cb=0x48b5fc
```

to have them available to the rtsp server

**Comment by gtxaspec** [comment]
app live view is broken again when more than one callback is hooked

**Comment by gtxaspec** [comment]
fixed function, everything works now, including with next release.

**Comment by Vendo232** [comment]
unable to make it work
![image](https://user-images.githubusercontent.com/44098230/168681309-c53362d4-0c4d-4d51-8901-6336eecf142c.png)

seems like stream is missing video
![image](https://user-images.githubusercontent.com/44098230/168681430-a886dd55-648d-4616-8f21-742b821fc034.png)

**Comment by gtxaspec** [comment]
which stream? both?

**Comment by gtxaspec** [comment]
just tested, working on latest release for me, both streams.

**Comment by Vendo232** [comment]
I can't get any working. Hmm , must be doing something wrong. Im using RTSP FW with RTSP off will check Standard FW

**Comment by gtxaspec** [comment]
haven't tested latest with the rtsp firmware...

I will test

**Comment by gtxaspec** [comment]
definitely worth upgrading to latest fw, there's no advantage to using the old rtsp one anymore from what I see, unless you have some feedback regarding that.

the latest fw has numerous performance related fixes tok

**Comment by Vendo232** [comment]
it works PERFECT!

**Comment by gtxaspec** [comment]
awesome! enjoy
