### ISSUE TITLE
Change config

### ISSUE THREAD

**Issue by jritsema** [gtxaspec/wz_mini_hacks#470]
Hello.  I didn't see it mentioned in the docs, but what is the intended way to change config (`SD_ROOT/wz_mini/wz_mini.conf`) options (e.g., change host name or RTSP creds)?

Is the intent to remove the sd card, delete all files, and replace it with a fresh config?

**Comment by xconverge** [comment]
Removing the SD card is one valid way although most inconvenient as you have found, I edited my config quite often over the ssh connection (/media/mmc/* with nano and reboot command), and there is also the webserver (https://github.com/gtxaspec/wz_mini_hacks#web-server) that lets you edit/reboot from the website for the camera too with some checkboxes and text boxes on the website.

You should not need to delete files and simply changing the config file and restarting should apply I think

**Comment by jritsema** [comment]
Awesome, that's what I was looking for.  Thanks @xconverge!
