### ISSUE TITLE
PAN V2 Vertical Tilt

### ISSUE THREAD

**Issue by bjs-pdx** [gtxaspec/wz_mini_hacks#477]
Just saw this after mounting my camera:

**Vertical Tilt on the PANv2 doesn't work properly. Only does this on the modified kernel. Need investigation why this happens.**

I need to adjust the vertical setting to a lower view since I have the camera hanging upside down.  Does anyone have suggestions on how I might accomplish this?

**Comment by endertable** [comment]
If cam is within reach, unplug cam, remove SD card, start cam normal and adjust view with app.  I believe the camera remembers its PT position between boots.  Then unplug cam, reinsert card, start cam.

**Comment by bjs-pdx** [comment]
Yes, thought about that.  However, it is a temporary solution.  I might want to change the view on the camera and don't want to go through that each time.

Is there any plan to fix the issue or is it going to just be that way?  If there isn't any plan to fix it I'd probably be better off using a fixed position V3.

**Comment by bjs-pdx** [comment]
The vertical tilt seems to work, sort of, if you set the motor speed to 9.  It is glitchy, but it does move.  It doesn't always go to the end, until you reboot the camera.

**Comment by wokawoka** [comment]
I see this issue as closed and already completed about one year ago, but I'm experiencing the problem on my PAN V2 running a recent verion of wz_mini_hacks.
Am I missing something? Do you have a suggestion?
Thank you!

**Comment by wokawoka** [comment]
apparently it looks still open here https://github.com/gtxaspec/wz_mini_hacks/issues/19
