### ISSUE TITLE
Noise - cmd aplay

### ISSUE THREAD

**Issue by baudev** [gtxaspec/wz_mini_hacks#492]
I notice that the `cmd aplay` command (with a .wav audio file present on the camera) makes a strange noise at the beginning and end of the audio file.  
This noise is also present when the camera says "WZ initializing" when installing wz_mini.

However, the camera does not make this strange noise if you use only the Wyze firmware. Does anyone know where it comes from?

Thanks

**Comment by gtxaspec** [comment]
i've noticed this varies by device, some do, and some don't.  could it be power supply related?

**Comment by gtxaspec** [comment]
@baudev Try a file, not in wav format, but raw pcm s16le 16000hz mono,  and no noise should happen.

**Comment by gtxaspec** [comment]
confirmed, playing raw pcm files without the wav header eliminated the click

**Comment by gtxaspec** [comment]
converted all sounds to raw pcm https://github.com/gtxaspec/wz_mini_hacks/commit/6cda362ee84350e8b3df62e64f22b485be80c16f

**Comment by baudev** [comment]
Thanks, I tried today and indeed it works perfectly 🎉
