### ISSUE TITLE
Unable to SSH/webserver into cam

### ISSUE THREAD

**Issue by admin-cooter** [gtxaspec/wz_mini_hacks#510]
### Discussed in https://github.com/gtxaspec/wz_mini_hacks/discussions/509

<div type='discussions-op-text'>

<sup>Originally posted by **admin-cooter** April 21, 2023</sup>
(Wyze Cam V3) SD setup went well but I am still unable to SSH or http(s) into the webserver. The Wyze cam is up and running and connected to the network and i have edited the config file to enable webserver, the only other changes are a few RTSP settings (Login/Pass/Port). Am i missing something super simple here? I can't help but feel like I am missing some super simple step here. What other reasons would be limiting my access to the device?

EDIT 1: Wyze app shows the cam SD card as detected. says its ip is 10.10.10 instead of normal 192.168 but router says its connected</div>

**Comment by gtxaspec** [comment]
sounds like a configuration issue? as long as you have your ssh keys in the authorized_keys file, it should work fine.  you could wipe the sd card and start over to see if it works.
