### ISSUE TITLE
Possible to add correct URLs in web config for v2 cameras?

### ISSUE THREAD

**Issue by flyize** [gtxaspec/wz_mini_hacks#534]
Since I'm very new to the project, it took me a loooong time to figure out that the URLs showing in the web config are wrong for v2 cameras.

**Comment by virmaior** [comment]
if you tell me the correct pattern I can update it -- at least on my fork.

**Comment by gtxaspec** [comment]
@virmaior if you want to make a pull request I'd be happy to merge back in 😀

**Comment by virmaior** [comment]
fixed in https://github.com/gtxaspec/wz_mini_hacks/pull/558

**Comment by gtxaspec** [comment]
updated in master.
