### ISSUE TITLE
rtmp_stream: migrate to go2rtc

### ISSUE THREAD

**Issue by gtxaspec** [gtxaspec/wz_mini_hacks#562]
`ffmpeg -y -i "rtsp://xxxxx:8554/1080p?mp4" -c:a copy -c:v copy -coder 1 -pix_fmt yuv420p -g 30 -bf 0 -framerate 30 -aspect 16:9 -f flv "rtmp://a.rtmp.youtube.com/live2/key"`
aac

**Comment by gtxaspec** [comment]
bug:  youtube live won't display full screen.  testing twitch and facebook next

**Comment by gtxaspec** [comment]
go2rtc is implementing push to RTMP, so we will deprecate our current method soon, once @AlexxIT finalizes a release =D

**Comment by AlexxIT** [comment]
I don't understand. There is bug with YouTube or not?

**Comment by gtxaspec** [comment]
No bug, I meant that YouTube is working fine, just waiting for an official release of go2rtc
