### ISSUE TITLE
ICamera cpu usage increased

### ISSUE THREAD

**Issue by vic4news** [gtxaspec/wz_mini_hacks#565]
Hi,
I installed the latest version of wz_mini_hacks on some of my v3 cams and noticed that the cpu usage of the ICamera process almost doubled. Is this expected? 

Btw, been using this code for over a year and it really makes the cameras usable

**Comment by gtxaspec** [comment]
for me: 
old release 60-80 cpu icamera usage
new release: same

what is your expected cpu usage?

**Comment by vic4news** [comment]
The cameras with the 09-27-22 version normally have cpu usage of 34% - 42%.
The cameras running the new version have cpu usage of 57% - 62%
The cameras record continuously to the sd card. Enable mp4 write is on.

**Comment by clee604** [comment]
Probably dumb question hut what are you using to monitor the usage?

I have a bunch of cameras I'm about to update so I can also do some comparisons.

**Comment by vic4news** [comment]
I’m just using the ‘top’ command

**Comment by dudududodododedede** [comment]
What time of day are you checking? For me the cpu usage is much higher during the day, and lower at night. I assume because there is less activity/visible detail at night

**Comment by stncttr908** [comment]
My CPU usage is the same after updating on all of my V3s

**Comment by gtxaspec** [comment]
closing for now, expected cpu usage for iCamera is  50-80 (it's a huge, cobbled together app that has tons of code)
reopen issue if further issues persist.
