### ISSUE TITLE
Upgrade script doesn't save go2rtc.yml

### ISSUE THREAD

**Issue by clee604** [gtxaspec/wz_mini_hacks#637]
I just upgraded a wyze V2 camera and the upgrade script doesn't seem to retain the previous go2rtc.yml and seems to overwrite with default file. I noticed because the V2 requires updating the video source in the go2rtc configuration.

I believe this also happens on the V3 since previously I've had to reapply my api and rtsp authentication settings but I haven't tried upgrading just yet to confirm this.

**Comment by gtxaspec** [comment]
good find, will fix.

**Comment by clee604** [comment]
Confirmed this also happens on V3

**Comment by gtxaspec** [comment]
fixed in latest master

**Comment by clee604** [comment]
Just tried an upgrade and the configuration wasn't saved. I believe in your code you have go2rtc.yaml when the file is named go2rtc.yml

**Comment by gtxaspec** [comment]
good catch my dev system is named differently.  updated master.

**Comment by gtxaspec** [comment]
@clee604 can you confirm it's fixed? =D

**Comment by archandanime** [comment]
It worked on my v3 [upgrade_wz_mini.log](https://github.com/gtxaspec/wz_mini_hacks/files/12928405/upgrade_wz_mini.log). go2rtc.yml file is preserved after upgrade, I'm not sure if it also works on v2 cameras.
```
...
+ cp /opt/Upgrade/preserve/cron/root /opt/wz_mini/etc/cron/
+ cp /opt/Upgrade/preserve/resolv.dnsmasq /opt/wz_mini/etc/resolv.dnsmasq
+ cp /opt/Upgrade/preserve/go2rtc.yml /opt/wz_mini/etc/go2rtc.yml
+ rm -rf /opt/Upgrade
+ sync
+ reboot
```

**Comment by gtxaspec** [comment]
The script should be the same on the v2... Thanks 🙂

**Comment by clee604** [comment]
I upgraded 5 cameras and 4 worked fine retaining the go2rtc.yml. The last errored out but I think it's a separate issue unrelated to this issue
