### ISSUE TITLE
camera audio/video tuning

### ISSUE THREAD

**Issue by gtxaspec** [gtxaspec/wz_mini_hacks#66]
testing libcallback with imp_control

`cmd imp_control <command> <value>`

| function name  | Value | Description |
| ------------- | ------------- | ----------- |
| __AUDIO__|
| agc_on  | <none>  | Enable Automatic Gain Control |
| agc_off  | <none>  | Disable Automatic Gain Control |
| hpf_on  | <none>  | Enable High Pass Filter |
| hpf_off  | <none>  | Disable High Pass Filter |
| ns_on | <none>  | Enable Noise Supression |
| ns_off  | <none>  | Disable Noise Supression |
| aec_on  | <none>  | Enable Automatic Echo Cancellation |
| aec_off  | <none>  | Disable Automatic Echo Cancellation |
| __VIDEO__|
| flip_mirror  | <none>  | Mirror Image |
| flip_vertical  | <none>  | Flip Vertical |
| flip_horizontal  | <none>  | Flip Horizontal |
| flip_normal  | <none>  | Normal Image |
| tune_contrast  | -128 to 128  | Contrast Control |
| tune_brightness  | -128 to 128 | Brightness Control |
| tune_sharpness  | -128 to 128 | Sharpness Control |
| tune_saturation  | -128 to 128 | Saturation Control |
| tune_aecomp  | 0 to 255 | Auto Exposure Target |
| tune_aeitmax  | 0 to 10000 | Auto Exposure Maxiumum |
| tune_dpc_strength | -128 to 128 | DPC Strength |
| tune_drc_strength | -128 to 128 | DRC Strength |
| tune_hilightdepress | 0 to 10 | Glare Supression |
| tune_temper | -128 to 128 | 3D Noise reduction strength |
| tune_sinter | -128 to 128 | 2D Noise reduction strength |
| tune_again | 0 to 99999 | Set sensor A-Gain maximum |
| tune_dgain | see notes | Maximum D-Gain set by the ISP |
| tune_backlightcomp | -1 to 3500 | Backlight Compensation? (undocumented) |

tune_dgain: 0 means 1x, 32 means 2x, and so on 

need help:
change framerate dynamically up to 30fps
change audio hz frequency dynamically up to 44100
change audio format from g711
move OSD to user specified region
white balance adjustment
enable wide dynamic range support
exposure value support

[libcallback.so.tar.gz](https://github.com/gtxaspec/wz_mini_hacks/files/8851931/libcallback.so.tar.gz)

**Comment by capncybo** [comment]
Awesome stuff, & forgive my ignorance but...
Is there already an integrated way (Or perhaps a combined terminal command) which can (play/pipe) "remote" audio over the Camera's built-in speaker.  In other words... to mimic the Microphone/Speaker feature **without** using the WYZE app.
Or to a lesser degree... stream audio which actually resides elsewhere?

**Comment by gtxaspec** [comment]
not sure if there is a way to do two way audio, but streaming audio from a source other than a file... hmm I will test with ffmpeg to see if it works.

**Comment by capncybo** [comment]
Thanks, I think within the WYZE API it's more like a Walkie Talkie (meaning One at a Time & Not Full Duplex) but...
It might INDEED be useful if we could stream audio from a remote source other than a file.

**Comment by gtxaspec** [comment]
not familiar with the api, maybe @mrlt8 has some familiarity with the api and has some knowledge about how the two way audio works?

**Comment by gtxaspec** [comment]
included in latest release.

**Comment by mrlt8** [comment]
The app reuses the same TUTK AVAPIs that it uses to stream audio/video from the camera, but this time sets up the avserver on the mobile device and uses avSendAudioData to push the audio to the camera.

**Comment by gtxaspec** [comment]
@capncybo  see https://github.com/gtxaspec/wz_mini_hacks/issues/68

**Comment by sibero80** [comment]
Is there a way to read the values of the `cmd imp_control` properties?
