### ISSUE TITLE
isolated network - timestamp is not correct, how to set time?

### ISSUE THREAD

**Issue by borgqueenx** [gtxaspec/wz_mini_hacks#673]
I have rejected outward traffic on my wyze cams, preventing them from accessing the internet.
I am using the RTSP firmware and enabled rtsp in the wyze app, selfhosted set to true in mini hacks.
However, i noticed that the timestamp of my wyze cam is now off by quite some hours, also quite some minutes.

I tried setting the date/time with the date command through ssh, but this setting is not saved. 
How do i proceed to set the date and time for the timestamp to be correct, also after a reboot?

thanks!

**Comment by borgqueenx** [comment]
> know: the system tries to connect to an ntp server. believe: the list is hard-wired into iCamera
> 
> solutions:
> 
> 1. give it a false dns pointing to your own ntp server
> 2. setup a cron job to have it get the time from a server under your control to set it.

for point 2, how do we set a time? i know that when using the date command in ssh, it will not update the timestamp in the rtsp stream, and a restart makes the set time invalid again, so the timestamp never gets changed.
with point 1, do you have some easy guide how to proceed with that to make this function? I have a Openwrt router that has ntp server enabled, so i could simply (or at least should) be able to use 192.168.1.1.

**Comment by virmaior** [comment]
set NTP_SERVER in wz_mini.conf

(see https://github.com/gtxaspec/wz_mini_hacks/blob/07c7f29b0ea3c637ef452db28136af670a2248d8/SD_ROOT/wz_mini/etc/init.d/S18ntp#L4 ) for where it happens.

**Comment by borgqueenx** [comment]
Thank you! Initially it didn't work, but when i specified the port (so 192.168.1.1:123) it worked!
Thank you for the assistance!

**Comment by borgqueenx** [comment]
Closing this issue then.

**Comment by amandamana** [comment]
I got stuck on the same problem until finding this post.

Ideally, the default port would be automatic if not specified.

Even more ideally, the NTP server address would be taken from the DHCP field if provided.
