### ISSUE TITLE
Feature request: Display wz_mini version on login

### ISSUE THREAD

**Issue by vic4news** [gtxaspec/wz_mini_hacks#688]
I would like to see the wz_mini version displayed when I ssh into the camera. 
For example, add the following to /etc/profile 

echo "wz_mini version:"
cat /opt/wz_mini/usr/bin/app.ver

**Comment by virmaior** [comment]
the contents of `/opt/wz_mini/etc/motd` are displayed automatically when you login.

could add a script to the boot process to copy over the version info.

**Comment by gtxaspec** [comment]
added!
