### ISSUE TITLE
 ASIX AX88179 USB 3.0 Gigibit Ethernet

### ISSUE THREAD

**Issue by Vendo232** [gtxaspec/wz_mini_hacks#7]
RTSP: 4.61.03
adapter:  ASIX AX88179 USB 3.0 Gigibit Ethernet
it takes ~ 2-3 minutes before LED lights go ON on the adapter, but when they do I`m unable to connect on WYZE app, on Frigate not I see the device on DHCP, or SSH

dmesg:

[    0.000000] Initializing cgroup subsys cpu
[    0.000000] Initializing cgroup subsys cpuacct
[    0.000000] Linux version 3.10.14__isvp_swan_1.0__ (root@5997f1cc9594) (gcc version 4.7.4 (Buildroot 2016.02) ) #28 PREEMPT Wed Apr 13 06:47:11 UTC 2022
[    0.000000] bootconsole [early0] enabled
[    0.000000] CPU0 RESET ERROR PC:005214B5
[    0.000000] CPU0 revision is: 00d00100 (Ingenic Xburst)
[    0.000000] FPU revision is: 00b70000
[    0.000000] cgu_get_rate, parent = 1392000000, rate = 0, m = 0, n = 0, reg val = 0x081000ff
[    0.000000] cgu_get_rate, parent = 1392000000, rate = 0, m = 0, n = 0, reg val = 0x081000ff
[    0.000000] CCLK:1392MHz L2CLK:696Mhz H0CLK:200MHz H2CLK:200Mhz PCLK:100Mhz
[    0.000000] Determined physical RAM map:
[    0.000000]  memory: 005c5000 @ 00010000 (usable)
[    0.000000]  memory: 0007b000 @ 005d5000 (usable after init)
[    0.000000] User-defined physical RAM map:
[    0.000000]  memory: 05000000 @ 00000000 (usable)
[    0.000000] Initrd not found or empty - disabling initrd
[    0.000000] Zone ranges:
[    0.000000]   Normal   [mem 0x00000000-0x04ffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x00000000-0x04ffffff]
[    0.000000] On node 0 totalpages: 20480
[    0.000000] free_area_init_node: node 0, pgdat 805d1a00, node_mem_map 81000000
[    0.000000]   Normal zone: 160 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 20480 pages, LIFO batch:3
[    0.000000] Primary instruction cache 32kB, 8-way, VIPT, linesize 32 bytes.
[    0.000000] Primary data cache 32kB, 8-way, VIPT, no aliases, linesize 32 bytes
[    0.000000] pls check processor_id[0x00d00100],sc_jz not support!
[    0.000000] MIPS secondary cache 128kB, 8-way, linesize 32 bytes.
[    0.000000] pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
[    0.000000] pcpu-alloc: [0] 0
[    0.000000] Built 1 zonelists in Zone order, mobility grouping off.  Total pages: 20320
[    0.000000] Kernel command line: console=ttyS1,115200n8 mem=80M@0x0 rmem=48M@0x5000000 rdinit=/init mtdparts=jz_sfc:256K(boot),1984K(kernel),3904K(rootfs),3904K(app),1984K(kback),3904K(aback),384K(cfg),64K(para)
[    0.000000] PID hash table entries: 512 (order: -1, 2048 bytes)
[    0.000000] Dentry cache hash table entries: 16384 (order: 4, 65536 bytes)
[    0.000000] Inode-cache hash table entries: 8192 (order: 3, 32768 bytes)
[    0.000000] Memory: 72860k/81920k available (4584k kernel code, 9060k reserved, 1321k data, 492k init, 0k highmem)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] Preemptible hierarchical RCU implementation.
[    0.000000] NR_IRQS:358
[    0.000000] clockevents_config_and_register success.
[    0.000014] Calibrating delay loop... 1391.00 BogoMIPS (lpj=6955008)
[    0.087830] pid_max: default: 32768 minimum: 301
[    0.092689] Mount-cache hash table entries: 512
[    0.097608] Initializing cgroup subsys debug
[    0.101864] Initializing cgroup subsys freezer
[    0.107315] devtmpfs: initialized
[    0.111478] regulator-dummy: no parameters
[    0.115724] NET: Registered protocol family 16
[    0.131160] bio: create slab <bio-0> at 0
[    0.136652] jz-dma jz-dma: JZ SoC DMA initialized
[    0.141572] usbcore: registered new interface driver usbfs
[    0.147158] usbcore: registered new interface driver hub
[    0.152555] usbcore: registered new device driver usb
[    0.157723]  (null): set:249  hold:250 dev=100000000 h=500 l=500
[    0.163806] media: Linux media interface: v0.10
[    0.168374] Linux video capture interface: v2.00
[    0.173182] Advanced Linux Sound Architecture Driver Initialized.
[    0.180510] Switching to clocksource jz_clocksource
[    0.185438] cfg80211: Calling CRDA to update world regulatory domain
[    0.192489] dwc2 otg probe start
[    0.192514] jz-dwc2 jz-dwc2: cgu clk gate get error
[    0.197434] DWC IN OTG MODE
[    0.200830] dwc2 dwc2: Keep PHY ON
[    0.204208] dwc2 dwc2: Using Buffer DMA mode
[    0.208522] dwc2 dwc2: Core Release: 3.00a
[    0.212714] dwc2 dwc2: DesignWare USB2.0 High-Speed Host Controller
[    0.219040] dwc2 dwc2: new USB bus registered, assigned bus number 1
[    0.226194] hub 1-0:1.0: USB hub found
[    0.229927] hub 1-0:1.0: 1 port detected
[    0.234028] dwc2 dwc2: DWC2 Host Initialized
[    0.238312] dwc2 otg probe success
[    0.238442] NET: Registered protocol family 2
[    0.243224] TCP established hash table entries: 1024 (order: 1, 8192 bytes)
[    0.250232] TCP bind hash table entries: 1024 (order: 0, 4096 bytes)
[    0.256731] TCP: Hash tables configured (established 1024 bind 1024)
[    0.263159] TCP: reno registered
[    0.266372] UDP hash table entries: 256 (order: 0, 4096 bytes)
[    0.272315] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
[    0.278839] NET: Registered protocol family 1
[    0.283446] RPC: Registered named UNIX socket transport module.
[    0.289374] RPC: Registered udp transport module.
[    0.294191] RPC: Registered tcp transport module.
[    0.298910] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.312711] dwc2 dwc2: ID PIN CHANGED!
[    0.503662] freq_udelay_jiffys[0].max_num = 10
[    0.508088] cpufreq  udelay  loops_per_jiffy
[    0.512576] 12000     59956   59956
[    0.515770] 24000     119913  119913
[    0.519213] 60000     299784  299784
[    0.522677] 120000    599569  599569
[    0.526188] 200000    999282  999282
[    0.529720] 300000    1498924         1498924
[    0.533508] 600000    2997848         2997848
[    0.537137] 792000    3957159         3957159
[    0.540845] 1008000   5036385         5036385
[    0.544679] 1200000   5995696         5995696
[    0.552614] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.559116] jffs2: version 2.2. © 2001-2006 Red Hat, Inc.
[    0.564946] msgmni has been set to 142
[    0.569606] io scheduler noop registered
[    0.573613] io scheduler cfq registered (default)
[    0.580079] jz-uart.1: ttyS1 at MMIO 0x10031000 (irq = 58) is a uart1
[    0.587736] console [ttyS1] enabled, bootconsole disabled
[    0.602052] brd: module loaded
[    0.606879] loop: module loaded
[    0.610611] zram: Created 2 device(s) ...
[    0.614943] logger: created 256K log 'log_main'
[    0.620030] jz TCU driver register completed
[    0.624791] the id code = 1c7018, the flash name is EN25QH128A
[    0.630817] JZ SFC Controller for SFC channel 0 driver register
[    0.636984] 8 cmdlinepart partitions found on MTD device jz_sfc
[    0.643124] Creating 8 MTD partitions on "jz_sfc":
[    0.648071] 0x000000000000-0x000000040000 : "boot"
[    0.653532] 0x000000040000-0x000000230000 : "kernel"
[    0.659121] 0x000000230000-0x000000600000 : "rootfs"
[    0.664722] 0x000000600000-0x0000009d0000 : "app"
[    0.669995] 0x0000009d0000-0x000000bc0000 : "kback"
[    0.675535] 0x000000bc0000-0x000000f90000 : "aback"
[    0.681022] 0x000000f90000-0x000000ff0000 : "cfg"
[    0.686384] 0x000000ff0000-0x000001000000 : "para"
[    0.691753] SPI NOR MTD LOAD OK
[    0.695077] tun: Universal TUN/TAP device driver, 1.6
[    0.700292] tun: (C) 1999-2004 Max Krasnyansky <maxk@qualcomm.com>
[    0.706831] usbcore: registered new interface driver zd1201
[    0.712669] usbcore: registered new interface driver r8152
[    0.718370] usbcore: registered new interface driver asix
[    0.724010] usbcore: registered new interface driver ax88179_178a
[    0.730411] usbcore: registered new interface driver usbserial
[    0.736515] usbcore: registered new interface driver pl2303
[    0.742305] usbserial: USB Serial support registered for pl2303
[    0.748714] wait stable.[289][cgu_msc0]
[    0.752718] jzmmc_v1.2 jzmmc_v1.2.0: vmmc regulator missing
[    0.758691] jzmmc_v1.2 jzmmc_v1.2.0: register success!
[    0.764030] jzmmc_v1.2 jzmmc_v1.2.0: card inserted, state=0
[    0.769863] jzmmc_v1.2 jzmmc_v1.2.1: vmmc regulator missing
[    0.775649] usb 1-1: new high-speed USB device number 2 using dwc2
[    0.782249] jzmmc_v1.2 jzmmc_v1.2.1: register success!
[    0.789661] wireguard: WireGuard 1.0.20200712 loaded. See www.wireguard.com for information.
[    0.798428] wireguard: Copyright (C) 2015-2019 Jason A. Donenfeld <Jason@zx2c4.com>. All Rights Reserved.
[    0.808529] TCP: cubic registered
[    0.812312] NET: Registered protocol family 10
[    0.817516] sit: IPv6 over IPv4 tunneling driver
[    0.822768] NET: Registered protocol family 17
[    0.828032] input: gpio-keys as /devices/platform/gpio-keys/input/input0
[    0.835202] drivers/rtc/hctosys.c: unable to open rtc device (rtc0)
[    0.841723] ALSA device list:
[    0.844841]   #0: Loopback 1
[    0.849715] Freeing unused kernel memory: 492K (805d5000 - 80650000)
[    1.021881] mmc0: new high speed SDHC card at address 0001
[    1.027799] mmcblk0: mmc0:0001 SD 29.1 GiB
[    1.033201]  mmcblk0: p1
[    2.304673] ax88179_178a 1-1:2.0 (unregistered net_device): Failed to write reg index 0x0002: -143
[    2.322675] ax88179_178a 1-1:2.0 (unregistered net_device): Failed to write reg index 0x0002: -143
[    2.541968] ax88179_178a 1-1:2.0 (unregistered net_device): Failed to write reg index 0x0001: -143
[    2.608783] @@@@ tx-isp-probe ok(version H20200506a), compiler date=May  6 2020 @@@@@
[    2.648489] exFAT: Version 1.2.9
[    2.651937] ax88179_178a 1-1:2.0 (unregistered net_device): Failed to read reg index 0x0006: -143
[    2.661103] ax88179_178a 1-1:2.0 (unregistered net_device): Failed to write reg index 0x0005: -143
[    2.674365] ax88179_178a 1-1:2.0 (unregistered net_device): Failed to write reg index 0x0001: -143
[    2.683750] ax88179_178a 1-1:2.0 (unregistered net_device): Failed to write reg index 0x0001: -143
[    2.693279] ax88179_178a 1-1:2.0 (unregistered net_device): Failed to write reg index 0x0001: -143
[    2.703101] ax88179_178a 1-1:2.0 (unregistered net_device): Failed to write reg index 0x0001: -143
[    2.712899] ax88179_178a 1-1:2.0 (unregistered net_device): Failed to write reg index 0x0002: -143
[    2.722693] ax88179_178a 1-1:2.0 (unregistered net_device): Failed to write reg index 0x0001: -143
[    2.732531] ax88179_178a 1-1:2.0 (unregistered net_device): Failed to write reg index 0x0002: -143
[    2.742331] ax88179_178a 1-1:2.0 (unregistered net_device): Failed to read reg index 0x0001: -143
[    2.752058] ax88179_178a 1-1:2.0 (unregistered net_device): Failed to write reg index 0x0001: -143
[    2.761922] ax88179_178a 1-1:2.0 (unregistered net_device): Failed to read reg index 0x0000: -143
[    2.780394] ax88179_178a 1-1:2.0 eth0: register 'ax88179_178a' at usb-dwc2-1, ASIX AX88179 USB 3.0 Gigibit Ethernet, 92:61:30:2e:c6:c0
[    2.808032] jz_codec_register: probe() successful!
[    2.813280] ax88179_178a 1-1:2.1 (unregistered net_device): Failed to write reg index 0x0002: -143
[    2.824111] cgu_set_rate, parent = 1392000000, rate = 2048000, n = 10875, reg val = 0x01002a7b
[    2.824124] cgu_enable,cgu_i2s_spk reg val = 0x21002a7b
[    2.824144] cgu_set_rate, parent = 1392000000, rate = 2048000, n = 10875, reg val = 0x01002a7b
[    2.824151] cgu_enable,cgu_i2s_mic reg val = 0x21002a7b
[    2.824195] ax88179_178a 1-1:2.1 (unregistered net_device): Failed to write reg index 0x0002: -143
[    3.232182] dma dma0chan24: Channel 24 have been requested.(phy id 7,type 0x06 desc a2439000)
[    3.241304] dma dma0chan25: Channel 25 have been requested.(phy id 6,type 0x06 desc a25b2000)
[    3.250514] dma dma0chan26: Channel 26 have been requested.(phy id 5,type 0x04 desc a247b000)
[    3.324644] __init
[    3.330526] jz_pwm_probe[255] d_name = tcu_chn0
[    3.336882] The version of PWM driver is H20180309a
[    3.347577] request pwm channel 0 successfully
[    3.353971] pwm-jz pwm-jz: jz_pwm_probe register ok !
[    3.367795] mmc1: card claims to support voltages below the defined range. These will be ignored.
[    3.386998] usbcore: registered new interface driver usb_ch34x
[    3.394702] ch34x: USB to serial driver for USB to serial chip ch340, ch341, etc.
[    3.402576] ch34x: V1.16 On 2020.12.23
[    3.412864] mmc1: new SDIO card at address 0001
[    3.672080] RTL871X: module init start
[    3.675963] RTL871X: rtl8189ftv v4.3.24.7_21113.20170208.nova.1.02
[    3.683696] RTL871X: build time: Dec 18 2020 16:40:08
[    3.688924] wlan power on by hualai
[    3.712027] RTL871X: ++++++++rtw_drv_init: vendor=0x024c device=0xf179 class=0x07
[    3.748113] RTL871X: HW EFUSE
[    3.751201] RTL871X: hal_com_config_channel_plan chplan:0x20
[    3.843054] RTL871X: rtw_regsty_chk_target_tx_power_valid return _FALSE for band:0, path:0, rs:0, t:-1
[    3.853693] RTL871X: rtw_ndev_init(wlan0) if1 mac_addr=78:f2:35:6c:b6:9c
[    3.871035] RTL871X: module init ret=0
[    6.118395] name : i2c0 nr : 0
[    6.202037] i2c i2c-0: i2c_jz_irq 441, I2C transfer error, ABORT interrupt
[    6.209159] i2c i2c-0: --I2C txabrt:
[    6.212870] i2c i2c-0: --I2C TXABRT[0]=I2C_TXABRT_ABRT_7B_ADDR_NOACK
[    6.219589] error: sensor_read,285 ret = -5
[    6.223946]  sensor_read: addr=0x3107 value = 0x0
[    6.228835] err sensor read addr = 0x3107, value = 0x0
[    6.322375]  sensor_read: addr=0xf0 value = 0x20
[    6.327635]  sensor_read: addr=0xf1 value = 0x53
[    6.332460] info: success sensor find : gc2053
[    6.337071] misc sinfo_release
[    6.428829] set sensor gpio as PA-low-10bit
[    6.434613] probe ok ------->gc2053
[    6.512371] -----gc2053_detect: 832 ret = 0, v = 0x20
[    6.512861] -----gc2053_detect: 838 ret = 0, v = 0x53
[    6.512870] gc2053 chip found @ 0x37 (i2c0)
[    6.730396] gc2053 stream on
[    6.819466] Err [VIC_INT] : hor err ch3 !!!!!
[    6.955357] cgu_set_rate, parent = 1392000000, rate = 4096000, n = 10875, reg val = 0x22002a7b
[    6.955369] codec_codec_ctl: set sample rate...
[    6.955964] codec_codec_ctl: set device...
[    7.371900] codec_set_device: set device: MIC...
[    7.378100] codec_codec_ctl: set repaly channel...
[    7.378146] cgu_set_rate, parent = 1392000000, rate = 4096000, n = 10875, reg val = 0x22002a7b
[    7.378154] codec_codec_ctl: set sample rate...
[    7.378457] codec_codec_ctl: set device...
[    7.611892] codec_set_device: set device: speaker...
[    7.619208] SPEAKER CTL MODE3 !
[    8.042019] ax88179_178a 1-1:2.1 (unregistered net_device): Failed to write reg index 0x0001: -145
[    8.963445] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   10.443161] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[   12.916157] RTL871X: rtw_set_802_11_connect(wlan0)  fw_state=0x00000008
[   12.943070] RTL871X: start auth
[   13.161946] ax88179_178a 1-1:2.1 (unregistered net_device): Failed to read reg index 0x0006: -145
[   16.175482] RTL871X: rtw_set_802_11_connect(wlan0)  fw_state=0x00000008
[   16.424685] RTL871X: start auth
[   16.441725] RTL871X: auth success, start assoc
[   18.172014] ax88179_178a 1-1:2.1 (unregistered net_device): Failed to write reg index 0x0005: -145
[   19.999313] RTL871X: rtw_set_802_11_connect(wlan0)  fw_state=0x00000008
[   20.216717] RTL871X: start auth
[   20.517578] RTL871X: auth success, start assoc
[   20.534454] RTL871X: assoc success
[   20.538445] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[   20.545240] RTL871X: recv eapol packet
[   21.050244] RTL871X: send eapol packet
[   21.066586] RTL871X: recv eapol packet
[   21.165883] RTL871X: recv eapol packet
[   21.365628] RTL871X: send eapol packet
[   21.370849] RTL871X: set pairwise key camid:4, addr:14:cc:20:da:4b:89, kid:0, type:AES
[   21.389656] RTL871X: send eapol packet
[   21.398193] RTL871X: set group key camid:5, addr:14:cc:20:da:4b:89, kid:1, type:AES
[   23.201986] ax88179_178a 1-1:2.1 (unregistered net_device): Failed to write reg index 0x0001: -145
[   28.212632] ax88179_178a 1-1:2.1 (unregistered net_device): Failed to write reg index 0x0001: -145
[   32.361749] run_mmc.sh start
[   33.241968] ax88179_178a 1-1:2.1 (unregistered net_device): Failed to write reg index 0x0001: -145
[   38.252309] ax88179_178a 1-1:2.1 (unregistered net_device): Failed to write reg index 0x0001: -145
[   43.261990] ax88179_178a 1-1:2.1 (unregistered net_device): Failed to write reg index 0x0002: -145
[   48.281998] ax88179_178a 1-1:2.1 (unregistered net_device): Failed to write reg index 0x0001: -145
[   53.292026] ax88179_178a 1-1:2.1 (unregistered net_device): Failed to write reg index 0x0002: -145
[   58.301975] ax88179_178a 1-1:2.1 (unregistered net_device): Failed to read reg index 0x0001: -145
[   63.311944] ax88179_178a 1-1:2.1 (unregistered net_device): Failed to write reg index 0x0001: -145
[   68.331967] ax88179_178a 1-1:2.1 (unregistered net_device): Failed to read reg index 0x0000: -145
[   68.346470] ax88179_178a 1-1:2.1 eth1: register 'ax88179_178a' at usb-dwc2-1, ASIX AX88179 USB 3.0 Gigibit Ethernet, 92:61:30:2e:c6:c0
[   68.362227] usb 1-1: USB disconnect, device number 2
[   68.377613] ax88179_178a 1-1:2.0 eth0: unregister 'ax88179_178a' usb-dwc2-1, ASIX AX88179 USB 3.0 Gigibit Ethernet
[   68.412003] ax88179_178a 1-1:2.0 (unregistered net_device): Failed to write reg index 0x0002: -19
[   68.432259] ax88179_178a 1-1:2.0 (unregistered net_device): Failed to write reg index 0x0001: -19
[   68.445930] ax88179_178a 1-1:2.0 (unregistered net_device): Failed to write reg index 0x0002: -19
[   68.457336] ax88179_178a 1-1:2.1 eth1: unregister 'ax88179_178a' usb-dwc2-1, ASIX AX88179 USB 3.0 Gigibit Ethernet
[   68.502058] ax88179_178a 1-1:2.1 (unregistered net_device): Failed to write reg index 0x0002: -19
[   68.511703] ax88179_178a 1-1:2.1 (unregistered net_device): Failed to write reg index 0x0001: -19
[   68.532280] ax88179_178a 1-1:2.1 (unregistered net_device): Failed to write reg index 0x0002: -19
[   68.891957] usb 1-1: new high-speed USB device number 3 using dwc2
[   69.893582] ax88179_178a 1-1:1.0 (unregistered net_device): Failed to read reg index 0x0040: -32
[   70.026910] ax88179_178a 1-1:1.0 eth0: register 'ax88179_178a' at usb-dwc2-1, ASIX AX88179 USB 3.0 Gigibit Ethernet, f8:e4:3b:2d:c1:17

**Comment by Vendo232** [comment]
lsusb
Bus 001 Device 003: ID 0b95:1790
Bus 001 Device 001: ID 1d6b:0002

ifconfig eth0
eth0      Link encap:Ethernet  HWaddr F8:E4:3B:2D:C1:17
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

[root@WCV3:~]#

**Comment by gtxaspec** [comment]
ok let me look into this.

**Comment by gtxaspec** [comment]
i ordered the USB adapter to test, stand by

**Comment by gtxaspec** [comment]
received the adapter, I was able to have make it work.  I'll include the fixes in the next release. @Vendo232

**Comment by gtxaspec** [comment]
this usb adapter is strange, it doesn't work properly when the plug is connected all the way in, I.E. the the usb 3.0 pins.  if you leave the connector just pushed in a bit, it works.  There are various reports online describing other issues with this adapter.  

I would recommend sticking with a USB 2.0 adapter for the camera's.  If you really want it to work ,don't push in the connector all the way and use the latest release.

**Comment by Vendo232** [comment]
thank you very much @gtxaspec
