### ISSUE TITLE
Firmware notes

### ISSUE THREAD

**Issue by amazeika** [gtxaspec/wz_mini_hacks#726]
Hello guys,

First off, thanks for all this, I'm about to jump in after a youtube video I've just saw and before purchasing the cameras I naturally went to the Firmware compatibility section just to be 100% sure that v3 is good to go. In there you have the following note for this model:

**Firmware 4.36.9.139 and Earlier for V3 and Floodlight: These versions support rooting the device, which includes access to a root shell and SSHD. However, functionalities like libcallback features, RTSP video streaming, and cmd commands are all not available.**

Now ... it seems, and after checking the history, that you mean that all these features that you list ARE NOT supported on newer versions (beyond x.139) ... this is not what the current note says and it's very misleading. 

I would really suggest to fix the wordings on this note as to properly reflect the limitations. In my particular case I need RTSP support enabled and this will work with 4.36.9.139 and earlier.

Thanks again guys, waiting for my cameras and hoping that everything will go smoothly :)

Cheers!

**Comment by gtxaspec** [comment]
updated! thanks.
