### ISSUE TITLE
How do I set the time zone for crontab to work as expected? Defaults to UTC

### ISSUE THREAD

**Issue by david-lloyd-neudesic** [gtxaspec/wz_mini_hacks#739]

**Comment by virmaior** [comment]
basically can't, because the device's internal time zone is UTC.

iCamera is decoding `/configs/TZ` (or `/etc/TZ`) but no busybox accessible function can decipher it.

**Comment by david-lloyd-neudesic** [comment]
Thank

> basically can't, because the device's internal time zone is UTC.
> 
> iCamera is decoding `/configs/TZ` (or `/etc/TZ`) but no busybox accessible function can decipher it.

Thanks virmairor!
