### ISSUE TITLE
WIKI Information for Config File Contains an error

### ISSUE THREAD

**Issue by bjs-pdx** [gtxaspec/wz_mini_hacks#758]
I was struggling to setup a new V3 camera with the most recent version of the files.  I was modifying the configuration file to enable features for the web server, but after I did, wz_mini_hacks wouldn't load.  I was copying the setting from the wiki but those settings contain an additional character (a single quote) so the camera would never boot (note the last character in the line below).  The extra character barely visible.

WEB_SERVER_OPTIONS="cam config car jpeg"`

![Screenshot 2024-04-08 at 11-54-48 Configuration File · gtxaspec_wz_mini_hacks Wiki](https://github.com/gtxaspec/wz_mini_hacks/assets/14082937/29f623ed-e6f5-432e-b420-954c1632b265)

**Comment by xOnlyFadi** [comment]
what version is ur v3 camera on?

**Comment by gtxaspec** [comment]
fixed!

**Comment by bjs-pdx** [comment]
> what version is ur v3 camera on?

![Screenshot 2024-04-09 at 08-02-12 T31(WYZE_CAKP2JFUS) on 4 36 9 139 running wz_mini Wed Sep 20 04 17 50 PM PDT 2023 as NEWV3](https://github.com/gtxaspec/wz_mini_hacks/assets/14082937/5fc45c64-7553-40eb-88f3-f91faa440260)
