### ISSUE TITLE
Wyze V2 audio play is distorted

### ISSUE THREAD

**Issue by my-umd** [gtxaspec/wz_mini_hacks#805]
I'm following [this instruction](https://github.com/gtxaspec/wz_mini_hacks/wiki/Audio-Playback) to make wav files (from mp3) for my V2.  But when I played it on the camera, it plays slower (like 50% slower), and a female voice would change to male voice.  I verified that the converted wav file plays fine on my computer.  Does anyone know what is going on?

**Comment by gtxaspec** [comment]
you need to use the right sample rate, check the samplerate of the files included, i think for the v2 it's 8000hz

**Comment by hua-bing** [comment]
Thanks @gtxaspec.  Using 8000 works.
BTW, the sample audio gives errors when trying to check the info.:
```
$ ffmpeg -i init_v2.wav
......
init_v2.wav: Invalid data found when processing input
```
Pls close the issue.  For some reason, I do not see an option for me to close it.
