### ISSUE TITLE
Change default authorized_keys filename to allow easier upgrading

### ISSUE THREAD

**Issue by tensiondriven** [gtxaspec/wz_mini_hacks#92]
I've run into the case where I wanted to update my camera(s) to a newer version of wz_mini_hacks.  In order to do that, I need to download the code and overwrite my cards with the contents of SD_ROOT.  Since the authorized_keys file is needed for remote access, right now I have to make sure not to clobber that file when I overwrite, or manually update it.

If instead of providing an authorized_keys file with a comment inside saying "Put your key here", the file was named something like authorized_keys.template, and included instructions ("rename this file to authorized keys and put your keys here"), then doing an overwrite of the SD Card with a new version of wz_mini_hacks would still allow me to SSH in and make modifications.  As it is, if i forget this, I have to take the card out, put it in a computer, and update the authorized_keys file manually.

I know there are other files that people might modify, and those would still get clobbered, but at least if this change was made, people could do those changes by shelling in, which is far easier when you have a fleet of cameras.

A longer term solution that provided some way to ota-update all SD_CARD files would be ideal, but this would be a good, simple stopgap that would prevent significant heartburn for people who are upgrading.

**Comment by claudobahn** [comment]
There's a work in progress update script that @gtxaspec has been testing which preserves the SSH config along w/ a few other things. You can try it out by calling `/opt/wz_mini/usr/bin/[upgrade-run.sh` and report back in the enhancement request for that: https://github.com/gtxaspec/wz_mini_hacks/issues/43

If there's nothing else, feel free to close this issue.

**Comment by gtxaspec** [comment]
the latest release has the upgrade script located at `/opt/wz_mini/usr/bin/upgrade-run.sh`, it works well.  I would upgrade manually, and then you can use that from now on.
