### ISSUE TITLE
Add SFTP support

### ISSUE THREAD

**Issue by archandanime** [gtxaspec/wz_mini_hacks#99]
It's very hassling to transfer files between the micro SD card and my computer. It would be very nice to copy-and-paste in Nautilus with SFTP, that saves a lot of time!

**Comment by gtxaspec** [comment]
dropbear (the ssh server we use) doesn't support sftp out of the box, but let me see what can be done

**Comment by skilau** [comment]
Just an added comment, just in case you weren't aware...

Since we have ssh natively built-in, you can always use "scp" to transfer files in and out of the Cam instead of sftp.
(I believe Nautilus has a plug-in for "scp")

**Comment by gtxaspec** [comment]
lets wait for #123 on this one
